In [1]:
%reload_ext autoreload
%autzoreload 2

UsageError: Line magic function `%autzoreload` not found.

In [2]:
import pandas as pd
# get the general sde synthethic data

sde_data_v2 = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/gen_data_stage3/instructor/data_v2/gpt-4o-mini")

sde_data_v2.rename(columns={
    "context": "_context",
}, inplace=True)

sde_data_v2.head()

,id,url1,title,text,prob_included,questions,_context,search_terms,request_tokens,response_tokens,total_tokens,time_taken
2846,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210418.html,APOD: 2021 April 18 - Rainbow Airglow over the...,APOD: 2021 April 18 - Rainbow Airglow over the...,0.999830,[What causes the sky to glow in the phenomenon...,"[Airglow. Now air glows all of the time, but i...","[airglow phenomenon, gravity waves in atmosphe...",1050.0,615.0,1665.0,10.073934
3347,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap221011.html,"APOD: 2022 October 11 - Stars, Dust, Pillars, ...","APOD: 2022 October 11 - Stars, Dust, Pillars, ...",0.999830,[What structures are found within the Pelican ...,"[On the whole, the nebula appears like a bird ...","[Pelican Nebula structure, Herbig-Haro jets ef...",1055.0,625.0,1680.0,10.069554
1288,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap160322.html,APOD: 2016 March 22 - Rainbow Airglow over the...,APOD: 2016 March 22 - Rainbow Airglow over the...,0.999829,[What causes airglow in the Earth's atmosphere...,"[Airglow . Now air glows all of the time, but ...","[airglow phenomena, colors of airglow, gravity...",1049.0,580.0,1629.0,9.792861
976,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap150422.html,APOD: 2015 April 22 - Colorful Star Clouds in ...,APOD: 2015 April 22 - Colorful Star Clouds in ...,0.999828,"[What is the primary subject of the April 22, ...",[Discover the cosmos! Each day a different ima...,"[star forming region Cygnus, Gamma Cygni nebul...",1012.0,417.0,1429.0,6.736070
2767,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210125.html,APOD: 2021 January 25 - Southern Cross over Ch...,APOD: 2021 January 25 - Southern Cross over Ch...,0.999828,[What astronomical feature is depicted in the ...,[The featured image was taken last month in Ch...,"[Southern Cross visibility, Villarrica volcano...",1058.0,558.0,1616.0,8.383144

In [3]:
# get the stratified sde synthethic data
sde_data_v3 = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/gen_data_stage3/instructor/data_v3/gpt-4o-mini")

sde_data_v3.rename(columns={
    "context": "_context",
}, inplace=True)

sde_data_v3.head()

,id,url1,title,text,prob_included,questions,_context,search_terms,request_tokens,response_tokens,total_tokens,time_taken
0,/SDE/cosmic_origins/|https://cor.gsfc.nasa.gov...,https://cor.gsfc.nasa.gov/news/2024/45_Roman_G...,News and Announcements - Roman Galactic Plane ...,Cosmic Origins (COR)\nSkip navigation and go s...,0.990796,[What is the purpose of seeking community inpu...,[The Roman Space Telescope team requests the s...,[Roman Galactic Plane General Astrophysics Sur...,2121.0,461.0,2582.0,8.842160
1,/SDE/hubble_space_telescope/|https://hubblesit...,https://hubblesite.org/contents/media/images/2...,Elliptical Galaxy NGC 4589 | HubbleSite,Elliptical Galaxy NGC 4589 | HubbleSite\nSkip ...,0.998942,[What is the distance from Earth to Elliptical...,[108 million light-years (33 million parsecs)],"[Elliptical Galaxy NGC 4589, distance to Ellip...",2351.0,91.0,2442.0,2.262768
2,/SDE/stsci_space_telescope_science_institute/|...,https://www.stsci.edu/jwst/phase2-public/2511.pdf,"JWST Proposal 2511 (Created: Wednesday, April ...","JWST Proposal 2511 (Created: Wednesday, April ...",0.997065,[What is the primary mission objective of JWST...,[We propose to explore the properties of small...,"[JWST Proposal 2511, II Zw 40 NIRSpec IFU, II ...",3441.0,731.0,4172.0,12.184392
3,/SDE/ned_nasa_ipac_extragalactic_database/|htt...,https://ned.ipac.caltech.edu/level5/March20/Ma...,Multi-scale simulations of particle accelerati...,Multi-scale simulations of particle accelerati...,0.995479,[What is the primary focus of the review by A....,[This review aims at providing an up-to-date s...,"[numerical study of particle acceleration, non...",2112.0,582.0,2694.0,9.797809
4,/SDE/cool_cosmos/|https://coolcosmos.ipac.calt...,https://coolcosmos.ipac.caltech.edu/ask/90-How...,How long does it take Jupiter to go around the...,How long does it take Jupiter to go around the...,0.999440,[How long does Jupiter take to complete one or...,[Jupiter revolves or orbits around the Sun onc...,"[How long does Jupiter take to orbit the Sun, ...",1763.0,448.0,2211.0,7.580638

In [4]:
sde_data_v2.columns, sde_data_v3.columns

(Index(['id', 'url1', 'title', 'text', 'prob_included', 'questions', '_context',
        'search_terms', 'request_tokens', 'response_tokens', 'total_tokens',
        'time_taken'],
       dtype='object'),
 Index(['id', 'url1', 'title', 'text', 'prob_included', 'questions', '_context',
        'search_terms', 'request_tokens', 'response_tokens', 'total_tokens',
        'time_taken'],
       dtype='object'))

In [5]:
# concat 
sde_data_v2["source"] = "SDE_general_v2"
sde_data_v3["source"] = "SDE_general_v3"
sde_data = pd.concat([sde_data_v2, sde_data_v3])
# remove data points with nan total_tokens
sde_data = sde_data[sde_data["total_tokens"].notna()]
sde_data.shape, sde_data["id"].nunique(),sde_data_v2.shape, sde_data_v3.shape
# expand / explode dataset

((19995, 13), 19995, (10000, 13), (10003, 13))

In [6]:
sde_data.head()

,id,url1,title,text,prob_included,questions,_context,search_terms,request_tokens,response_tokens,total_tokens,time_taken,source
2846,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210418.html,APOD: 2021 April 18 - Rainbow Airglow over the...,APOD: 2021 April 18 - Rainbow Airglow over the...,0.999830,[What causes the sky to glow in the phenomenon...,"[Airglow. Now air glows all of the time, but i...","[airglow phenomenon, gravity waves in atmosphe...",1050.0,615.0,1665.0,10.073934,SDE_general_v2
3347,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap221011.html,"APOD: 2022 October 11 - Stars, Dust, Pillars, ...","APOD: 2022 October 11 - Stars, Dust, Pillars, ...",0.999830,[What structures are found within the Pelican ...,"[On the whole, the nebula appears like a bird ...","[Pelican Nebula structure, Herbig-Haro jets ef...",1055.0,625.0,1680.0,10.069554,SDE_general_v2
1288,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap160322.html,APOD: 2016 March 22 - Rainbow Airglow over the...,APOD: 2016 March 22 - Rainbow Airglow over the...,0.999829,[What causes airglow in the Earth's atmosphere...,"[Airglow . Now air glows all of the time, but ...","[airglow phenomena, colors of airglow, gravity...",1049.0,580.0,1629.0,9.792861,SDE_general_v2
976,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap150422.html,APOD: 2015 April 22 - Colorful Star Clouds in ...,APOD: 2015 April 22 - Colorful Star Clouds in ...,0.999828,"[What is the primary subject of the April 22, ...",[Discover the cosmos! Each day a different ima...,"[star forming region Cygnus, Gamma Cygni nebul...",1012.0,417.0,1429.0,6.736070,SDE_general_v2
2767,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210125.html,APOD: 2021 January 25 - Southern Cross over Ch...,APOD: 2021 January 25 - Southern Cross over Ch...,0.999828,[What astronomical feature is depicted in the ...,[The featured image was taken last month in Ch...,"[Southern Cross visibility, Villarrica volcano...",1058.0,558.0,1616.0,8.383144,SDE_general_v2

# QA explosion

In [7]:
import json
# generate QA pairs

sde_qa_pairs = sde_data.explode(['questions', '_context']).reset_index(drop=True)
sde_qa_pairs = sde_qa_pairs.rename(columns={'questions': 'query', '_context': 'context'})

sde_qa_pairs["type"] = "question-answer"
sde_qa_pairs["synthesized"] = True



def create_qa_metadata(row):
    metadata = {
        "id": row.get('id'),
        "url1": row.get('url1'),
        "title": row.get('title'),
        "text": row.get('text'),
        "prob_included": float(row.get('prob_included')),
        "source": row.get('source'),
        "search_terms": list(row.get('search_terms')),
        "request_tokens": int(row.get('request_tokens')),
        "response_tokens": int(row.get('response_tokens')),
        "total_tokens": float(row.get('total_tokens')),
        "time_taken": float(row.get('time_taken'))
    }
    return metadata

sde_qa_pairs["metadata"] = sde_qa_pairs.apply(create_qa_metadata, axis=1).apply(json.dumps)


columns_to_keep = ["query", "context", "type", "synthesized", "source", "metadata", "url1"]
sde_qa_pairs = sde_qa_pairs[columns_to_keep]
sde_qa_pairs.head()

,query,context,type,synthesized,source,metadata,url1
0,What causes the sky to glow in the phenomenon ...,"Airglow. Now air glows all of the time, but it...",question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
1,What are the likely origins of the colors seen...,"OK, but where do the colors originate? The dee...",question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
2,Where was the featured image of airglow captured?,The featured image was captured during a climb...,question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
3,Which galaxies can be seen in the image captur...,A spectacular sky is visible through this band...,question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
4,What results from disturbances like approachin...,A disturbance however -- like an approaching s...,question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html

In [8]:
sde_qa_pairs.shape

(177486, 7)

# search_term explosion

In [9]:
sde_data.head()

,id,url1,title,text,prob_included,questions,_context,search_terms,request_tokens,response_tokens,total_tokens,time_taken,source
2846,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210418.html,APOD: 2021 April 18 - Rainbow Airglow over the...,APOD: 2021 April 18 - Rainbow Airglow over the...,0.999830,[What causes the sky to glow in the phenomenon...,"[Airglow. Now air glows all of the time, but i...","[airglow phenomenon, gravity waves in atmosphe...",1050.0,615.0,1665.0,10.073934,SDE_general_v2
3347,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap221011.html,"APOD: 2022 October 11 - Stars, Dust, Pillars, ...","APOD: 2022 October 11 - Stars, Dust, Pillars, ...",0.999830,[What structures are found within the Pelican ...,"[On the whole, the nebula appears like a bird ...","[Pelican Nebula structure, Herbig-Haro jets ef...",1055.0,625.0,1680.0,10.069554,SDE_general_v2
1288,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap160322.html,APOD: 2016 March 22 - Rainbow Airglow over the...,APOD: 2016 March 22 - Rainbow Airglow over the...,0.999829,[What causes airglow in the Earth's atmosphere...,"[Airglow . Now air glows all of the time, but ...","[airglow phenomena, colors of airglow, gravity...",1049.0,580.0,1629.0,9.792861,SDE_general_v2
976,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap150422.html,APOD: 2015 April 22 - Colorful Star Clouds in ...,APOD: 2015 April 22 - Colorful Star Clouds in ...,0.999828,"[What is the primary subject of the April 22, ...",[Discover the cosmos! Each day a different ima...,"[star forming region Cygnus, Gamma Cygni nebul...",1012.0,417.0,1429.0,6.736070,SDE_general_v2
2767,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210125.html,APOD: 2021 January 25 - Southern Cross over Ch...,APOD: 2021 January 25 - Southern Cross over Ch...,0.999828,[What astronomical feature is depicted in the ...,[The featured image was taken last month in Ch...,"[Southern Cross visibility, Villarrica volcano...",1058.0,558.0,1616.0,8.383144,SDE_general_v2

In [10]:
import numpy as np

sde_search_pairs = sde_data.explode(['search_terms']).reset_index(drop=True)
sde_search_pairs = sde_search_pairs.rename(columns={'search_terms': 'query', 'text': 'context'})

sde_search_pairs["type"] = "search_term-document"
sde_search_pairs["synthesized"] = True


# A helper function to convert numpy types to native Python types
def convert_to_native_python_types(obj):
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    # You can add more checks for other numpy types if needed
    if isinstance(obj, (np.int64, np.int32)):
        return int(obj)
    if isinstance(obj, (np.float64, np.float32)):
        return float(obj)
    # If the object is not a numpy type, return it as is
    return obj


def create_search_metadata(row):
    metadata = {
        "id": row.get('id'),
        "url1": row.get('url1'),
        "title": row.get('title'),
        "text": row.get('text'),
        "prob_included": float(row.get('prob_included')),
        "source": row.get('source'),
        # Apply the conversion to each item in the list
        "questions": [convert_to_native_python_types(q) for q in row.get('questions', [])],
        "_context": [convert_to_native_python_types(c) for c in row.get('_context', [])],
        "request_tokens": int(row.get('request_tokens')),
        "response_tokens": int(row.get('response_tokens')),
        "total_tokens": float(row.get('total_tokens')),
        "time_taken": float(row.get('time_taken'))
    }
    return metadata

columns_to_keep = ["query", "context", "type", "synthesized", "source", "metadata", "url1"]

sde_search_pairs["metadata"] = sde_search_pairs.apply(create_search_metadata, axis=1).apply(json.dumps)
sde_search_pairs = sde_search_pairs[columns_to_keep]
sde_search_pairs.head()

# query	context	type	synthesized	source	metadata	url1

,query,context,type,synthesized,source,metadata,url1
0,airglow phenomenon,APOD: 2021 April 18 - Rainbow Airglow over the...,search_term-document,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
1,gravity waves in atmosphere,APOD: 2021 April 18 - Rainbow Airglow over the...,search_term-document,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
2,color origins of airglow,APOD: 2021 April 18 - Rainbow Airglow over the...,search_term-document,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
3,airglow observation techniques,APOD: 2021 April 18 - Rainbow Airglow over the...,search_term-document,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
4,ultraviolet light effects on OH molecules,APOD: 2021 April 18 - Rainbow Airglow over the...,search_term-document,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html

In [11]:
sde_search_pairs.shape

(194382, 7)

# CMR Search-term explosion

In [12]:
import pandas as pd
import json 
cmr_search_pair = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/gen_data_stage3/instructor/data_v4/gpt-4o-mini")
cmr_search_pair.head()

,query,context,type,synthesized,source,metadata,search_terms,request_tokens,response_tokens,total_tokens,time_taken
0,'Latent reserves' within the Swiss NFI,Description: The files refer to the data used ...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C2789815280-ENVIDAT"", ""t...",[latent reserves in National Forest Inventorie...,896,114,1010,1.673601
1,0.5 hour 1 M HCl extraction data for the Windm...,Description: These results are for the 0.5 hou...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C1214305813-AU_AADC"", ""t...","[4 hour HCl extraction method, 1 M HCl extract...",937,103,1040,1.512745
2,10 Days Synthesis of SPOT VEGETATION Images (V...,Description: The VGT-S10 are near-global or co...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C2207472890-FEDEO"", ""tre...","[SPOT-Vegetation agriculture monitoring, VGT-S...",631,119,750,1.644376
3,10 m firn temperature data: LGB traverses 1990-95,Description: The Lambert Glacier Basin (LGB) s...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C1214313574-AU_AADC"", ""t...","[Lambert Glacier Basin oversnow traverse data,...",796,127,923,1.793678
4,10 year trend of levels of organochlorine poll...,Description: Metadata record for data from ASA...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C1214305884-AU_AADC"", ""t...",[Antarctic organochlorine contamination levels...,1435,143,1578,2.619888

In [13]:
cmr_search_pair["type"] = "search_term-document"
cmr_search_pair["synthesized"] = True
cmr_search_pair["metadata"] = cmr_search_pair["metadata"].apply(json.loads)
cmr_search_pair["metadata"] = cmr_search_pair.apply(lambda r: {**r["metadata"], "request_tokens": r["request_tokens"], "response_tokens": r["response_tokens"], "total_tokens": r["total_tokens"], "time_taken": r["time_taken"]}, axis=1).apply(json.dumps)

In [14]:
cmr_search_pair.head()

,query,context,type,synthesized,source,metadata,search_terms,request_tokens,response_tokens,total_tokens,time_taken
0,'Latent reserves' within the Swiss NFI,Description: The files refer to the data used ...,search_term-document,True,CMR,"{""id"": ""/SDE/CMR_API/|C2789815280-ENVIDAT"", ""t...",[latent reserves in National Forest Inventorie...,896,114,1010,1.673601
1,0.5 hour 1 M HCl extraction data for the Windm...,Description: These results are for the 0.5 hou...,search_term-document,True,CMR,"{""id"": ""/SDE/CMR_API/|C1214305813-AU_AADC"", ""t...","[4 hour HCl extraction method, 1 M HCl extract...",937,103,1040,1.512745
2,10 Days Synthesis of SPOT VEGETATION Images (V...,Description: The VGT-S10 are near-global or co...,search_term-document,True,CMR,"{""id"": ""/SDE/CMR_API/|C2207472890-FEDEO"", ""tre...","[SPOT-Vegetation agriculture monitoring, VGT-S...",631,119,750,1.644376
3,10 m firn temperature data: LGB traverses 1990-95,Description: The Lambert Glacier Basin (LGB) s...,search_term-document,True,CMR,"{""id"": ""/SDE/CMR_API/|C1214313574-AU_AADC"", ""t...","[Lambert Glacier Basin oversnow traverse data,...",796,127,923,1.793678
4,10 year trend of levels of organochlorine poll...,Description: Metadata record for data from ASA...,search_term-document,True,CMR,"{""id"": ""/SDE/CMR_API/|C1214305884-AU_AADC"", ""t...",[Antarctic organochlorine contamination levels...,1435,143,1578,2.619888

In [15]:
# remove columns: request_tokens	response_tokens	total_tokens	time_taken
cmr_search_pair.drop(columns=["request_tokens", "response_tokens", "total_tokens", "time_taken"], inplace=True)

# remove query
cmr_search_pair.drop(columns=["query"], inplace=True)

# explode search_terms
cmr_search_pair = cmr_search_pair.explode(['search_terms']).reset_index(drop=True)

# rename search_terms as query
cmr_search_pair.rename(columns={'search_terms': 'query'}, inplace=True)

In [16]:
cmr_search_pair["url1"] = cmr_search_pair["metadata"].apply(lambda x: ".".join(json.loads(x).get("download_url", "").split(".")[:-1]))

In [17]:
cmr_search_pair = cmr_search_pair[["query", "context", "type", "synthesized", "source", "metadata", "url1"]]

In [18]:
cmr_search_pair.head()

# query	context	type	synthesized	source	metadata	url1

,query,context,type,synthesized,source,metadata,url1
0,latent reserves in National Forest Inventories,Description: The files refer to the data used ...,search_term-document,True,CMR,"{""id"": ""/SDE/CMR_API/|C2789815280-ENVIDAT"", ""t...",https://cmr.earthdata.nasa.gov/search/concepts...
1,criteria for identifying latent reserves,Description: The files refer to the data used ...,search_term-document,True,CMR,"{""id"": ""/SDE/CMR_API/|C2789815280-ENVIDAT"", ""t...",https://cmr.earthdata.nasa.gov/search/concepts...
2,Swiss National Forest Inventory database,Description: The files refer to the data used ...,search_term-document,True,CMR,"{""id"": ""/SDE/CMR_API/|C2789815280-ENVIDAT"", ""t...",https://cmr.earthdata.nasa.gov/search/concepts...
3,deciduous forest species composition,Description: The files refer to the data used ...,search_term-document,True,CMR,"{""id"": ""/SDE/CMR_API/|C2789815280-ENVIDAT"", ""t...",https://cmr.earthdata.nasa.gov/search/concepts...
4,tree mortality in near-natural forests,Description: The files refer to the data used ...,search_term-document,True,CMR,"{""id"": ""/SDE/CMR_API/|C2789815280-ENVIDAT"", ""t...",https://cmr.earthdata.nasa.gov/search/concepts...

In [19]:
cmr_search_pair.shape

(796097, 7)

# PDS search term explosion

In [20]:
import pandas as pd
import json 

pds_search_pair = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/gen_data_stage3/instructor/data_v5/gpt-4o-mini")
pds_search_pair.head()

,query,context,type,synthesized,source,metadata,search_terms,request_tokens,response_tokens,total_tokens,time_taken
0,Laboratory Study of Hydrocarbon IR Spectra Bundle,Description: ________\nTarget: Laboratory Anal...,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:lab.hydroc...","[hydrocarbon IR spectra laboratory study, cros...",712,58,770,1.975481
1,Mars 2020 MOXIE Bundle,Description: Bundle for the Mars 2020 Mars In-...,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:mars2020_m...","[Mars 2020 MOXIE experiment datasets, Mars Oxy...",674,52,726,1.498889
2,"Dust Devil Field Study in El Dorado Valley, Ne...",Description: Dust devil field campaign in El D...,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:eldorado_n...","[Dust Devil Field Observation Campaign, Lorenz...",680,40,720,1.906004
3,InSight EDL Bundle,Description: This PDS4 bundle contains the InS...,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:insight_ed...","[InSight EDL atmospheric reconstruction, Mars ...",652,41,693,1.766255
4,KPNO McMath-Pierce Solar Telescope Observation...,Description: McMath-Pierce Solar Telescope spe...,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:mcmath-pie...",[McMath-Pierce Solar Telescope Mercury observa...,679,54,733,2.173329

In [21]:
pds_search_pair["type"] = "search_term-document"
pds_search_pair["synthesized"] = True
pds_search_pair["metadata"] = pds_search_pair["metadata"].apply(json.loads)
pds_search_pair["metadata"] = pds_search_pair.apply(lambda r: {**r["metadata"], "request_tokens": r["request_tokens"], "response_tokens": r["response_tokens"], "total_tokens": r["total_tokens"], "time_taken": r["time_taken"]}, axis=1).apply(json.dumps)

In [22]:
pds_search_pair.head()

,query,context,type,synthesized,source,metadata,search_terms,request_tokens,response_tokens,total_tokens,time_taken
0,Laboratory Study of Hydrocarbon IR Spectra Bundle,Description: ________\nTarget: Laboratory Anal...,search_term-document,True,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:lab.hydroc...","[hydrocarbon IR spectra laboratory study, cros...",712,58,770,1.975481
1,Mars 2020 MOXIE Bundle,Description: Bundle for the Mars 2020 Mars In-...,search_term-document,True,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:mars2020_m...","[Mars 2020 MOXIE experiment datasets, Mars Oxy...",674,52,726,1.498889
2,"Dust Devil Field Study in El Dorado Valley, Ne...",Description: Dust devil field campaign in El D...,search_term-document,True,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:eldorado_n...","[Dust Devil Field Observation Campaign, Lorenz...",680,40,720,1.906004
3,InSight EDL Bundle,Description: This PDS4 bundle contains the InS...,search_term-document,True,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:insight_ed...","[InSight EDL atmospheric reconstruction, Mars ...",652,41,693,1.766255
4,KPNO McMath-Pierce Solar Telescope Observation...,Description: McMath-Pierce Solar Telescope spe...,search_term-document,True,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:mcmath-pie...",[McMath-Pierce Solar Telescope Mercury observa...,679,54,733,2.173329

In [23]:
# remove columns: request_tokens	response_tokens	total_tokens	time_taken
pds_search_pair.drop(columns=["request_tokens", "response_tokens", "total_tokens", "time_taken"], inplace=True)

# remove query
pds_search_pair.drop(columns=["query"], inplace=True)

# explode search_terms
pds_search_pair = pds_search_pair.explode(['search_terms']).reset_index(drop=True)

# rename search_terms as query
pds_search_pair.rename(columns={'search_terms': 'query'}, inplace=True)

pds_search_pair["url1"] = ""

pds_search_pair = pds_search_pair[["query", "context", "type", "synthesized", "source", "metadata", "url1"]]

In [24]:
pds_search_pair.head()

# query	context	type	synthesized	source	metadata	url1

,query,context,type,synthesized,source,metadata,url1
0,hydrocarbon IR spectra laboratory study,Description: ________\nTarget: Laboratory Anal...,search_term-document,True,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:lab.hydroc...",
1,cross section IR spectroscopy hydrocarbons pla...,Description: ________\nTarget: Laboratory Anal...,search_term-document,True,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:lab.hydroc...",
2,Bruker IFS 125HR Fourier Transform Spectromete...,Description: ________\nTarget: Laboratory Anal...,search_term-document,True,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:lab.hydroc...",
3,terahertz far-infrared beamline observations,Description: ________\nTarget: Laboratory Anal...,search_term-document,True,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:lab.hydroc...",
4,laboratory analogs of Jupiter Saturn and Titan,Description: ________\nTarget: Laboratory Anal...,search_term-document,True,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:lab.hydroc...",

In [25]:
pds_search_pair.shape

(52777, 7)

# CMR title description pairs

In [26]:
import pandas as pd

cmr_title_description = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/cmr_pairs_structured.parquet")
cmr_title_description["url1"] = ""
cmr_title_description.head()

# query	context	type	synthesized	source	metadata	url1

,query,context,type,synthesized,source,metadata,url1
0,'Latent reserves' within the Swiss NFI,Description: The files refer to the data used ...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C2789815280-ENVIDAT"", ""t...",
1,0.5 hour 1 M HCl extraction data for the Windm...,Description: These results are for the 0.5 hou...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C1214305813-AU_AADC"", ""t...",
2,10 Days Synthesis of SPOT VEGETATION Images (V...,Description: The VGT-S10 are near-global or co...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C2207472890-FEDEO"", ""tre...",
3,10 m firn temperature data: LGB traverses 1990-95,Description: The Lambert Glacier Basin (LGB) s...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C1214313574-AU_AADC"", ""t...",
4,10 year trend of levels of organochlorine poll...,Description: Metadata record for data from ASA...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C1214305884-AU_AADC"", ""t...",

In [27]:
cmr_title_description.shape

(53974, 7)

# PDS title description pairs

In [28]:
import pandas as pd

pds_title_description = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/pds_pairs_structured.parquet")
pds_title_description["url1"] = ""
pds_title_description.head()

,query,context,type,synthesized,source,metadata,url1
0,Laboratory Study of Hydrocarbon IR Spectra Bundle,Description: ________\nTarget: Laboratory Anal...,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:lab.hydroc...",
1,Mars 2020 MOXIE Bundle,Description: Bundle for the Mars 2020 Mars In-...,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:mars2020_m...",
2,"Dust Devil Field Study in El Dorado Valley, Ne...",Description: Dust devil field campaign in El D...,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:eldorado_n...",
3,InSight EDL Bundle,Description: This PDS4 bundle contains the InS...,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:insight_ed...",
4,KPNO McMath-Pierce Solar Telescope Observation...,Description: McMath-Pierce Solar Telescope spe...,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:mcmath-pie...",

In [29]:
pds_title_description.shape

(9832, 7)

# combine  / concat all datasets

In [30]:
df = pd.concat([sde_qa_pairs, sde_search_pairs, cmr_search_pair, pds_search_pair, cmr_title_description, pds_title_description], ignore_index=True)

In [31]:
df.head()

,query,context,type,synthesized,source,metadata,url1
0,What causes the sky to glow in the phenomenon ...,"Airglow. Now air glows all of the time, but it...",question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
1,What are the likely origins of the colors seen...,"OK, but where do the colors originate? The dee...",question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
2,Where was the featured image of airglow captured?,The featured image was captured during a climb...,question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
3,Which galaxies can be seen in the image captur...,A spectacular sky is visible through this band...,question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
4,What results from disturbances like approachin...,A disturbance however -- like an approaching s...,question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html

In [32]:
df.shape

(1284548, 7)

In [33]:
df.to_parquet("/rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_full_data", index=False)

# held out test set for benchmark

In [1]:
import pandas as pd

df = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_full_data.parquet")
df.head()

,query,context,type,synthesized,source,metadata,url1
0,What causes the sky to glow in the phenomenon ...,"Airglow. Now air glows all of the time, but it...",question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
1,What are the likely origins of the colors seen...,"OK, but where do the colors originate? The dee...",question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
2,Where was the featured image of airglow captured?,The featured image was captured during a climb...,question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
3,Which galaxies can be seen in the image captur...,A spectacular sky is visible through this band...,question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html
4,What results from disturbances like approachin...,A disturbance however -- like an approaching s...,question-answer,True,SDE_general_v2,"{""id"": ""/SDE/astronomy_picture_of_the_day/|htt...",https://apod.nasa.gov/apod/ap210418.html

In [2]:
from sklearn.model_selection import train_test_split

stratify_key =   df['type'].astype(str) + '_' + df['synthesized'].astype(str) + '_' + df['source'].astype(str)
train_df, test_df = train_test_split(df, test_size=0.1, random_state=42, shuffle=True, stratify=stratify_key)

In [3]:
train_df.shape, test_df.shape

((1156093, 7), (128455, 7))

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1284548 entries, 0 to 1284547
Data columns (total 7 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   query        1284540 non-null  object
 1   context      1284547 non-null  object
 2   type         1284548 non-null  object
 3   synthesized  1284548 non-null  bool
 4   source       1284548 non-null  object
 5   metadata     1284548 non-null  object
 6   url1         1276596 non-null  object
dtypes: bool(1), object(6)
memory usage: 60.0+ MB

In [5]:
# df[["type", "synthesized", "source"]].describe()
def inspect_data_distribution(dataframes, columns_to_check):
    """
    Calculates and compares the percentage of unique values for specified columns
    across multiple dataframes.

    Args:
        dataframes (dict): A dictionary where keys are names (e.g., 'Original', 'Train')
                           and values are the pandas DataFrames to compare.
        columns_to_check (list): A list of column names to analyze.
    """
    print("--- Comparing Data Distributions ---\n")
    
    for column in columns_to_check:
        print(f"--- Comparison for Column: '{column}' ---")
        
        # Create a dictionary to hold the value counts series for each dataframe
        dist_dict = {}
        for name, df in dataframes.items():
            dist_dict[name] = df[column].value_counts(normalize=True) * 100
        
        # Combine the series into a single comparison DataFrame
        comparison_df = pd.DataFrame(dist_dict).fillna(0)
        
        # Print formatted results
        print(comparison_df.to_string(float_format='%.4f%%'))
        print("\n" + "="*50 + "\n")

inspect_data_distribution({"df": df, "train": train_df, "test": test_df}, ["type", "synthesized", "source"])

--- Comparing Data Distributions ---

--- Comparison for Column: 'type' ---
                           df    train     test
type
search_term-document 81.2158% 81.2158% 81.2160%
question-answer      13.8170% 13.8170% 13.8173%
title-description     4.9672%  4.9672%  4.9667%

==================================================

--- Comparison for Column: 'synthesized' ---
                  df    train     test
synthesized
True        95.0328% 95.0328% 95.0333%
False        4.9672%  4.9672%  4.9667%

==================================================

--- Comparison for Column: 'source' ---
                     df    train     test
source
CMR            66.1767% 66.1767% 66.1765%
SDE_general_v2 15.0650% 15.0650% 15.0652%
SDE_general_v3 13.8843% 13.8844% 13.8842%
PDS             4.8740%  4.8740%  4.8741%

==================================================

In [6]:
df.shape, train_df.shape, test_df.shape

((1284548, 7), (1156093, 7), (128455, 7))

In [13]:
# saving the data frames
train_df.to_parquet(
    "/rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_st_train_corpus_data.parquet"
    ,compression='snappy', engine='pyarrow'
    )

In [8]:
test_df.to_parquet("/rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_st_test_corpus_data.parquet")

In [14]:
!ls -lh /rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_st_train_corpus_data.parquet

-rw-r--r-- 1 sawale sawale 2.3G Jun 27 11:05 /rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_st_train_corpus_data.parquet

In [15]:
!ls -lh /rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_full_data.parquet

-rw-r--r-- 1 sawale sawale 789M Jun 26 07:28 /rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_full_data.parquet

# converting it to standard jsonal format

In [2]:
import pandas as pd
import json
# need to check the metadata keys.
# some metadata liek time, reponse_tokens are related to synthsized data only and has nothing to do with corpus

# need to sperate metaa keys related to courpus, qrel and query

df = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_full_data")

df["metadata"] = df["metadata"].apply(json.loads)

# collect the keys in the metadata
metadata_keys = set()
for metadata in df["metadata"]:
    if isinstance(metadata, dict):
        metadata_keys.update(metadata.keys())
metadata_keys = sorted(metadata_keys)
print("Metadata keys:", metadata_keys)

Metadata keys: ['_context', 'agency', 'cmr_phenomena', 'data_product_desc', 'dataformat', 'download_url', 'id', 'instrument', 'investigation', 'pds_lid', 'platform', 'prob_included', 'purposes', 'questions', 'repository', 'request_tokens', 'response_tokens', 'scientific_keywords_1', 'search_terms', 'source', 'text', 'time_taken', 'title', 'total_tokens', 'treepath', 'url1']

In [ ]:
# related to corpus
# ['_context', 'agency', 'cmr_phenomena', 'data_product_desc', 'dataformat', 'download_url', 'id', 'instrument', 'investigation', 'pds_lid', 'platform', 'prob_included', 'purposes', 'repository', 'scientific_keywords_1', 'source', 'title', 'treepath', 'url1', 'text']

# might need to remove them
# 'questions' # when we have search_terms data point
# 'search_terms' # when we have qa data point

# query related (gen data related)
#  'request_tokens', 'response_tokens'
#  'time_taken' 'total_tokens'

In [3]:
# remove questions and search_terms from the dict of metadata column if it exists
def clean_metadata(metadata):
    if isinstance(metadata, dict):
        metadata.pop('questions', None)
        metadata.pop('search_terms', None)
    return metadata

df["metadata"] = df["metadata"].apply(clean_metadata)

In [4]:
# make a new column called corpus_metadata which will have the corpus related metadata
def extract_corpus_metadata(metadata):
    corpus_metadata = {
        key: metadata[key] for key in metadata if key in [
            '_context', 'agency', 'cmr_phenomena', 'data_product_desc', 
            'dataformat', 'download_url', 'id', 'instrument', 
            'investigation', 'pds_lid', 'platform', 'prob_included', 
            'purposes', 'repository', 'scientific_keywords_1', 
            'source', 'title', 'treepath', 'url1', 'text'
        ]
    }
    return corpus_metadata

df["corpus_metadata"] = df["metadata"].apply(extract_corpus_metadata)

In [5]:
# collect the keys in the metadata
metadata_keys = set()
for metadata in df["corpus_metadata"]:
    if isinstance(metadata, dict):
        metadata_keys.update(metadata.keys())
metadata_keys = sorted(metadata_keys)
print("Metadata keys:", metadata_keys)

Metadata keys: ['_context', 'agency', 'cmr_phenomena', 'data_product_desc', 'dataformat', 'download_url', 'id', 'instrument', 'investigation', 'pds_lid', 'platform', 'prob_included', 'purposes', 'repository', 'scientific_keywords_1', 'source', 'text', 'title', 'treepath', 'url1']

In [6]:
# make a new column called query_metadata which will have the query related metadata
def extract_query_metadata(metadata):
    query_metadata = {
        key: metadata[key] for key in metadata if key in [
            'request_tokens', 'response_tokens', 'time_taken', 'total_tokens'
        ]
    }
    return query_metadata
df["query_metadata"] = df["metadata"].apply(extract_query_metadata)

In [7]:
# again there are columns that need to be added to corresponding metadata
# add columsn like type, synthesized, source gors to existing query_metadata

def add_query_metadata_columns(row):
    query_metadata = row["query_metadata"]
    query_metadata["type"] = row["type"]
    query_metadata["synthesized"] = row["synthesized"]
    query_metadata["source"] = row["source"]
    return query_metadata

df["query_metadata"] = df.apply(add_query_metadata_columns, axis=1)

In [8]:
# drop type	synthesized	source metadata url1 
df.drop(columns=["type", "synthesized", "source", "metadata", "url1"], inplace=True)

df.head()

,query,context,corpus_metadata,query_metadata
0,What causes the sky to glow in the phenomenon ...,"Airglow. Now air glows all of the time, but it...",{'id': '/SDE/astronomy_picture_of_the_day/|htt...,"{'request_tokens': 1050, 'response_tokens': 61..."
1,What are the likely origins of the colors seen...,"OK, but where do the colors originate? The dee...",{'id': '/SDE/astronomy_picture_of_the_day/|htt...,"{'request_tokens': 1050, 'response_tokens': 61..."
2,Where was the featured image of airglow captured?,The featured image was captured during a climb...,{'id': '/SDE/astronomy_picture_of_the_day/|htt...,"{'request_tokens': 1050, 'response_tokens': 61..."
3,Which galaxies can be seen in the image captur...,A spectacular sky is visible through this band...,{'id': '/SDE/astronomy_picture_of_the_day/|htt...,"{'request_tokens': 1050, 'response_tokens': 61..."
4,What results from disturbances like approachin...,A disturbance however -- like an approaching s...,{'id': '/SDE/astronomy_picture_of_the_day/|htt...,"{'request_tokens': 1050, 'response_tokens': 61..."

In [14]:
import pandas as pd
import json
import os
import numpy as np

def sanitize_metadata(metadata):
    """
    Recursively sanitizes a metadata dictionary to ensure all primitive
    values are strings, preventing type errors during dataset loading.

    Args:
        metadata: The dictionary or list to sanitize.

    Returns:
        The sanitized dictionary or list.
    """
    if isinstance(metadata, dict):
        return {str(k): sanitize_metadata(v) for k, v in metadata.items()}
    elif isinstance(metadata, list):
        return [sanitize_metadata(elem) for elem in metadata]
    elif metadata is None:
        return None
    # Convert all other primitive types (int, float, bool) to string
    elif not isinstance(metadata, str):
        return str(metadata)
    return metadata


def create_sentence_transformer_dataset(
    df: pd.DataFrame,
    output_dir: str = "huggingface_dataset",
    train_split: float = 0.90,
    val_split: float = 0.05,
    random_state: int = 42
):
    """
    Shuffles, splits, and converts a DataFrame into the JSONL and TSV format
    for sentence-transformer models, while sanitizing metadata to prevent
    type errors during loading.

    Args:
        df (pd.DataFrame): Input DataFrame with columns 'query', 'context',
                           'query_metadata', 'corpus_metadata'.
        output_dir (str): Directory to save the dataset files.
        train_split (float): Proportion for the training set.
        val_split (float): Proportion for the validation set.
        random_state (int): Seed for reproducible shuffling.
    """
    # --- 0. Validate Splits ---
    test_split = 1.0 - train_split - val_split
    if not np.isclose(train_split + val_split + test_split, 1.0):
        raise ValueError("Train, validation, and test splits must sum to 1.0")
    if train_split <= 0 or val_split < 0 or test_split < 0:
        raise ValueError("Train split must be positive, and val/test splits must be non-negative.")

    # --- 1. Shuffle and Split DataFrame ---
    df_shuffled = df.sample(frac=1, random_state=random_state)
    train_end = int(train_split * len(df_shuffled))
    val_end = int((train_split + val_split) * len(df_shuffled))
    train_df, val_df, test_df = df_shuffled.iloc[:train_end], df_shuffled.iloc[train_end:val_end], df_shuffled.iloc[val_end:]
    print(f"Dataset split: {len(train_df)} train, {len(val_df)} validation, {len(test_df)} test examples.")

    # --- 2. Create Output Directories ---
    qrels_dir = os.path.join(output_dir, "qrels")
    os.makedirs(qrels_dir, exist_ok=True)
    print(f"Created directory structure at: {output_dir}")

    # --- 3. Generate Master Corpus and Queries Files ---
    corpus_dict = {}
    corpus_id_counter = 0
    print("Generating master corpus.jsonl and queries.jsonl files with sanitized metadata...")

    with open(os.path.join(output_dir, "corpus.jsonl"), "w", encoding="utf-8") as corpus_file, \
         open(os.path.join(output_dir, "queries.jsonl"), "w", encoding="utf-8") as queries_file:

        for i, row in df_shuffled.iterrows():
            query_id = f"q{i}"
            context_text = row['context']

            # Sanitize metadata before using it
            sanitized_corpus_meta = sanitize_metadata(row['corpus_metadata'])
            sanitized_query_meta = sanitize_metadata(row['query_metadata'])

            # Process and write corpus entry (if unique)
            if context_text not in corpus_dict:
                corpus_id_counter += 1
                corpus_id = f"c{corpus_id_counter}"
                corpus_dict[context_text] = corpus_id
                corpus_entry = {
                    "_id": corpus_id, "text": context_text, "title": "",
                    "metadata": sanitized_corpus_meta
                }
                corpus_file.write(json.dumps(corpus_entry) + "\n")

            # Process and write query entry
            query_entry = {
                "_id": query_id, "text": row['query'],
                "metadata": sanitized_query_meta
            }
            queries_file.write(json.dumps(query_entry) + "\n")

    # --- 4. Generate Qrels Files for Each Split ---
    def write_qrels(split_df, split_name):
        print(f"Generating qrels/{split_name}.tsv...")
        with open(os.path.join(qrels_dir, f"{split_name}.tsv"), "w", encoding="utf-8") as qrels_file:
            qrels_file.write("query-id\tcorpus-id\tscore\n")
            for i, row in split_df.iterrows():
                query_id = f"q{i}"
                corpus_id = corpus_dict[row['context']]
                qrels_file.write(f"{query_id}\t{corpus_id}\t1\n")

    write_qrels(train_df, "train")
    if not val_df.empty: write_qrels(val_df, "val")
    if not test_df.empty: write_qrels(test_df, "test")

    print("\nSuccessfully finished generating dataset files.")

In [15]:
# --- Run the Conversion ---
output_folder = "/rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_full_data_jsonl"

create_sentence_transformer_dataset(df, output_folder)

Dataset split: 1156093 train, 64227 validation, 64228 test examples.
Created directory structure at: /rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_full_data_jsonl
Generating master corpus.jsonl and queries.jsonl files with sanitized metadata...
Generating qrels/train.tsv...
Generating qrels/val.tsv...
Generating qrels/test.tsv...

Successfully finished generating dataset files.

In [1]:
from datasets import load_dataset, DatasetDict

# Define the path to your generated dataset directory
output_dir = "/rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/stage2_sde_full_data_jsonl"

# Load the corpus and queries
corpus = load_dataset('json', data_files=f'{output_dir}/corpus.jsonl', split='train')
queries = load_dataset('json', data_files=f'{output_dir}/queries.jsonl', split='train')

# Load the query-relevance (qrels) files for each split
# The separator is a tab ('\t')
qrels_train = load_dataset('csv', data_files=f'{output_dir}/qrels/train.tsv', sep='\t', split='train')
qrels_val = load_dataset('csv', data_files=f'{output_dir}/qrels/val.tsv', sep='\t', split='train')
qrels_test = load_dataset('csv', data_files=f'{output_dir}/qrels/test.tsv', sep='\t', split='train')


print("--- Loaded Corpus ---")
print(corpus)
# Example: print(corpus[0])

print("\n--- Loaded Queries ---")
print(queries)
# Example: print(queries[0])


print("\n--- Loaded Qrels (Train Split) ---")
print(qrels_train)
# Example: print(qrels_train[0])

--- Loaded Corpus ---
Dataset({
    features: ['_id', 'text', 'title', 'metadata'],
    num_rows: 188902
})

--- Loaded Queries ---
Dataset({
    features: ['_id', 'text', 'metadata'],
    num_rows: 1284548
})

--- Loaded Qrels (Train Split) ---
Dataset({
    features: ['query-id', 'corpus-id', 'score'],
    num_rows: 1156093
})

In [21]:
from datasets import load_dataset
from huggingface_hub import hf_hub_download
import json
import pandas as pd

dataset_name = "nasa-impact/nasa-sde-corpus"

dataset = load_dataset(dataset_name)
train_df = dataset["train"].to_pandas()
val_df = dataset["validation"].to_pandas()
test_df = dataset["test"].to_pandas()

queries_df = load_dataset(dataset_name, data_files="queries.jsonl", split="train").to_pandas()
queries_df.rename(columns={"_id": "query-id", "text": "query"}, inplace=True)

corpus_df = load_dataset(dataset_name, data_files="corpus.jsonl", split="train").to_pandas()
corpus_df.rename(columns={"_id": "corpus-id", "text": "corpus"}, inplace=True)

# Join for validation set
val_df = val_df.merge(queries_df, on="query-id", how="left")
val_df = val_df.merge(corpus_df, on="corpus-id", how="left")

# Join for test set
test_df = test_df.merge(queries_df, on="query-id", how="left")
test_df = test_df.merge(corpus_df, on="corpus-id", how="left")

Generating train split: 0 examples [00:00, ? examples/s]

,_id,text,metadata
0,q302327,Next Generation Sequencing methods,"{'request_tokens': '20162', 'response_tokens':..."
1,q496067,community interaction plan for marine geology,"{'request_tokens': '1026', 'response_tokens': ..."
2,q803374,paleoclimate indicators from tree rings,"{'request_tokens': '856', 'response_tokens': '..."
3,q586250,humidity water vapor indicators,"{'request_tokens': '991', 'response_tokens': '..."
4,q724674,sponges role in coral reef biology,"{'request_tokens': '618', 'response_tokens': '..."
...,...,...,...
1284543,q110268,What is the central wavelength of the Br gamma...,"{'request_tokens': '2336', 'response_tokens': ..."
1284544,q259178,Nebula distance from Earth,"{'request_tokens': '971', 'response_tokens': '..."
1284545,q131932,What is the ecological significance of the tun...,"{'request_tokens': '4114', 'response_tokens': ..."
1284546,q671155,ecotoxicology of sub-Antarctic soils,"{'request_tokens': '764', 'response_tokens': '..."
1284547,q121958,How does the altered proteome of Daphnia magna...,"{'request_tokens': '1439', 'response_tokens': ..."

In [12]:
test_df

,query-id,corpus-id,score,query,metadata_x,corpus,title,metadata_y
0,q230381,c46391,1,NASA Astrobiology Institute overview,"{'request_tokens': '899', 'response_tokens': '...",| NASA Astrobiology Institute\nNotice: This is...,,{'id': '/SDE/astrobiology_at_nasa/|https://ast...
1,q544704,c61521,1,EMIT greenhouse gas algorithm theoretical basis,"{'request_tokens': '1024', 'response_tokens': ...",Description: The Earth Surface Mineral Dust So...,,"{'id': '/SDE/CMR_API/|C2867824144-LPCLOUD', 't..."
2,q790962,c11754,1,climatic variations from tree rings,"{'request_tokens': '866', 'response_tokens': '...",Description: This archived Paleoclimatology St...,,"{'id': '/SDE/CMR_API/|C2103585925-NOAA_NCEI', ..."
3,q193092,c79617,1,Cocoon Nebula IC 5146,"{'request_tokens': '1028', 'response_tokens': ...",APOD: 2022 October 26 - Cocoon Nebula Wide Fie...,,{'id': '/SDE/astronomy_picture_of_the_day/|htt...
4,q229324,c100394,1,current trends in astrobiology research,"{'request_tokens': '921', 'response_tokens': '...",| NASA Astrobiology Institute\nNotice: This is...,,{'id': '/SDE/astrobiology_at_nasa/|https://ast...
...,...,...,...,...,...,...,...,...
64223,q110268,c188900,1,What is the central wavelength of the Br gamma...,"{'request_tokens': '2336', 'response_tokens': ...","Central Wavelength 2132, 2168.",,{'id': '/SDE/astropix/|https://www.astropix.or...
64224,q259178,c69715,1,Nebula distance from Earth,"{'request_tokens': '971', 'response_tokens': '...",APOD: 2017 August 2 - The Dust Monster in IC 1...,,{'id': '/SDE/astronomy_picture_of_the_day/|htt...
64225,q131932,c188901,1,What is the ecological significance of the tun...,"{'request_tokens': '4114', 'response_tokens': ...",The tundra-taiga boundary stretches for more t...,,{'id': '/SDE/misr_multi_angle_imaging_spectror...
64226,q671155,c20037,1,ecotoxicology of sub-Antarctic soils,"{'request_tokens': '764', 'response_tokens': '...",Description: Soil cores were collected from nu...,,"{'id': '/SDE/CMR_API/|C1299545142-AU_AADC', 't..."
64227,q121958,c188902,1,How does the altered proteome of Daphnia magna...,"{'request_tokens': '1439', 'response_tokens': ...",A comparative analysis of the proteome of Daph...,,{'id': '/SDE/GENELAB_METADATA_OSDR/|9dd65e414a...

In [16]:
import wandb
import pandas as pd

# --- Configuration: SET THESE VALUES ---
# 1. Path of the run you want to copy (e.g., "team-a/source-project/abc123xyz")
SOURCE_RUN_PATH = "nasa-impact/nasa_st_traning/9olox5mz" 

# 2. Name of the new destination project
DESTINATION_PROJECT = "nasa-indus-sde-s2"

# 3. Name of the destination entity (your username or team name)
DESTINATION_ENTITY = "impact-ibm-collaboration"

# 4. (Optional) Name for the new run. If None, W&B will generate one.
NEW_RUN_NAME = "stage1" 
# --- End of Configuration ---


def copy_run(source_run_path, dest_entity, dest_project, new_run_name=None):
    """
    Copies a W&B run to a new project.

    This function fetches the config, summary, metrics history, and files
    from a source run and logs them to a new run in the destination.
    
    Args:
        source_run_path (str): The path of the source run (entity/project/run_id).
        dest_entity (str): The entity (username or team) for the new run.
        dest_project (str): The project name for the new run.
        new_run_name (str, optional): A specific name for the new run. Defaults to None.
    """
    try:
        # Initialize the W&B API
        api = wandb.Api()
        
        print(f"Fetching source run: {source_run_path}")
        source_run = api.run(source_run_path)

        # --- 1. Fetch Configuration and Summary ---
        source_config = source_run.config
        source_summary = source_run.summary._json_dict

        # --- 2. Initialize the New Run ---
        new_run = wandb.init(
            project=dest_project,
            entity=dest_entity,
            config=source_config,
            name=new_run_name,
            reinit=True # Use reinit=True if running in a notebook
        )
        print(f"Created new run: {new_run.path}")

        # --- 3. Fetch and Log Metrics History ---
        print("Fetching and logging metrics history...")
        history_df = source_run.history()
        
        # Stream the history back to the new run
        for index, row in history_df.iterrows():
            # Convert row to a dictionary and filter out NaNs and the _step column
            log_dict = {k: v for k, v in row.to_dict().items() if pd.notna(v) and k != '_step'}
            wandb.log(log_dict, step=int(row['_step']))

        # --- 4. Fetch, Download, and Log Files/Artifacts ---
        print("Copying saved files and artifacts...")
        for f in source_run.files():
            # Download the file to the local directory
            f.download(replace=True)
            
            # Log files saved with wandb.save() to the new run
            if f.name.startswith('code/') or f.name in ['config.yaml', 'output.log', 'requirements.txt']:
                 # These are system files, log them carefully or skip
                 pass # Often better to let the new run generate its own system files
            else:
                wandb.save(f.name)

        # For artifacts (versioned data/models)
        for artifact in source_run.logged_artifacts():
            # To simply link the artifact to the new run without re-uploading:
            new_run.use_artifact(artifact)
            # If you want to create a new, distinct version of the artifact in the new project:
            # (This is less common for a simple copy)
            # downloaded_artifact = new_run.use_artifact(artifact.name)
            # new_artifact = wandb.Artifact(name=downloaded_artifact.name.split(':')[0], type=downloaded_artifact.type)
            # new_artifact.add_dir(downloaded_artifact.download())
            # new_run.log_artifact(new_artifact)

        # --- 5. Update the Final Summary ---
        wandb.summary.update(source_summary)

        # --- 6. Finish the New Run ---
        new_run.finish()
        print(f"\n✅ Successfully copied run to: {new_run.url}")

    except Exception as e:
        print(f"An error occurred: {e}")
        if 'new_run' in locals() and new_run is not None:
            new_run.finish(exit_code=1) # Mark the new run as crashed


# --- Run the copy process ---
if __name__ == "__main__":
    copy_run(
        source_run_path=SOURCE_RUN_PATH,
        dest_entity=DESTINATION_ENTITY,
        dest_project=DESTINATION_PROJECT,
        new_run_name=NEW_RUN_NAME
    )

Fetching source run: nasa-impact/nasa_st_traning/9olox5mz

wandb: Currently logged in as: sajil (impact-ibm-collaboration) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

Created new run: impact-ibm-collaboration/nasa-indus-sde-s2/58a5ee2a
Fetching and logging metrics history...
Copying saved files and artifacts...

✅ Successfully copied run to: https://wandb.ai/impact-ibm-collaboration/nasa-indus-sde-s2/runs/58a5ee2a