In [1]:
%reload_ext autoreload
%autoreload 2

In [1]:
import pandas as pd

dx_gpt_4o_mini = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/gen_data_stage3/instructor/data_v2/gpt-4o-mini")

# dx_gpt_41_mini = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/gen_data_stage3/instructor/data_v1/gpt-4.1-mini")


# dx_llama_3_2 = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/gen_data_stage3/instructor/data_v1/llama3.2:3b")
# dx.to_json("test.json", orient="records", lines=True)

In [3]:
dx_gpt_4o_mini

,id,url1,title,text,prob_included,questions,context,search_terms,request_tokens,response_tokens,total_tokens,time_taken
2846,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210418.html,APOD: 2021 April 18 - Rainbow Airglow over the...,APOD: 2021 April 18 - Rainbow Airglow over the...,0.999830,[What causes the sky to glow in the phenomenon...,"[Airglow. Now air glows all of the time, but i...","[airglow phenomenon, gravity waves in atmosphe...",1050.0,615.0,1665.0,10.073934
3347,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap221011.html,"APOD: 2022 October 11 - Stars, Dust, Pillars, ...","APOD: 2022 October 11 - Stars, Dust, Pillars, ...",0.999830,[What structures are found within the Pelican ...,"[On the whole, the nebula appears like a bird ...","[Pelican Nebula structure, Herbig-Haro jets ef...",1055.0,625.0,1680.0,10.069554
1288,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap160322.html,APOD: 2016 March 22 - Rainbow Airglow over the...,APOD: 2016 March 22 - Rainbow Airglow over the...,0.999829,[What causes airglow in the Earth's atmosphere...,"[Airglow . Now air glows all of the time, but ...","[airglow phenomena, colors of airglow, gravity...",1049.0,580.0,1629.0,9.792861
976,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap150422.html,APOD: 2015 April 22 - Colorful Star Clouds in ...,APOD: 2015 April 22 - Colorful Star Clouds in ...,0.999828,"[What is the primary subject of the April 22, ...",[Discover the cosmos! Each day a different ima...,"[star forming region Cygnus, Gamma Cygni nebul...",1012.0,417.0,1429.0,6.736070
2767,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210125.html,APOD: 2021 January 25 - Southern Cross over Ch...,APOD: 2021 January 25 - Southern Cross over Ch...,0.999828,[What astronomical feature is depicted in the ...,[The featured image was taken last month in Ch...,"[Southern Cross visibility, Villarrica volcano...",1058.0,558.0,1616.0,8.383144
...,...,...,...,...,...,...,...,...,...,...,...,...
225641,/SDE/NASA_Earth_Observatory/|https://earthobse...,https://earthobservatory.nasa.gov/images/14215...,Dust Plumes Off North Africa Coast November 14...,Dust Plumes Off North Africa Coast\nDust and H...,0.999791,[What natural phenomenon was observed flowing ...,[Streamers of dust flow out over the blue wate...,"[North African dust plumes, Mediterranean Sea ...",1029.0,578.0,1607.0,10.181799
127904,/SDE/nasa_science/|https://science.nasa.gov/re...,https://science.nasa.gov/resource/sol-2994-rig...,"Sol 2994: Right Navigation Camera, Cylindrical...","Sol 2994: Right Navigation Camera, Cylindrical...",0.999791,[What did the Curiosity rover create using the...,[NASA's Mars rover Curiosity took 29 images in...,"[Curiosity rover mosaic creation, Mars Curiosi...",1300.0,529.0,1829.0,13.256710
229260,/SDE/NASA_Earth_Observatory/|https://earthobse...,https://earthobservatory.nasa.gov/images/17685...,"Haze along the Himalaya November 28, 2006",Haze along the Himalaya\nDust and Haze\nSea an...,0.999791,[What atmospheric condition contributed to tra...,[Atmospheric pressure could be responsible for...,"[haze in the Himalayas, MODIS satellite imager...",1089.0,489.0,1578.0,10.243371
32105,/SDE/astrobiology_at_nasa/|https://astrobiolog...,https://astrobiology.nasa.gov/nai/directory/ol...,| NASA Astrobiology Institute,| NASA Astrobiology Institute\nNotice: This is...,0.999791,"[What type of research tool is Micro*scope?, W...",[Micro*scope (http://www.mbl.edu/microscope) -...,"[microbial diversity research tools, NASA Astr...",945.0,475.0,1420.0,7.999155
271214,/SDE/NASA_Earth_Observatory/|https://earthobse...,https://earthobservatory.nasa.gov/images/20350...,"Dust Storm over the Persian Gulf August 14, 2008",Dust Storm over the Persian Gulf\nDust and Haz...,0.999791,[What caused the dust storm over the Persian G...,[A dust storm blew over the Persian Gulf in mi...,"[Persian Gulf dust storm 2008, NASA MODIS Terr...",1061.0,642.0,1703.0,10.848794

In [3]:
dx_gpt_4o_mini[["request_tokens", "response_tokens", "total_tokens", "time_taken"]].sum()

request_tokens     1.064292e+07
response_tokens    5.159565e+06
total_tokens       1.580248e+07
time_taken         9.356118e+04
dtype: float64

In [75]:
dx_gpt_4o_mini.iloc[0]["questions"]

array(['What causes the sky to glow in colors like a rainbow?',
       'How is the deep red glow in airglow generated?',
       'What elements are responsible for orange and green airglow?',
       'Where was the image of Rainbow Airglow captured?',
       'What is visible in the banded airglow of the featured image?',
       'What phenomenon in the atmosphere can make airglow noticeable?',
       'What do gravity waves in air refer to?',
       'What is the significance of long-duration exposure in capturing airglow?',
       'What was the role of ground lights in the featured image?',
       'Who were the authors of the Astronomy Picture of the Day for April 18, 2021?'],
      dtype=object)

In [61]:
dx_gpt_41_mini.iloc[0]["questions"]

array(['What causes the sky to glow with a giant repeating rainbow pattern according to the explanation?',
       "What are gravity waves in the Earth's atmosphere and how are they formed?",
       'What molecules and atoms are responsible for the different colors observed in the airglow?',
       'Where was the image of the rainbow airglow captured?',
       'What celestial features are visible in the image along with the airglow?',
       'What is airglow and how is it usually perceived?',
       'How does a disturbance like an approaching storm affect the visibility of airglow?',
       'What is the height at which OH molecules generate the deep red airglow and what excites them?',
       'What causes the orange and green colors in the airglow and at what relative altitude do they occur?',
       'What is the geographical setting of the image and what ground lights are visible?'],
      dtype=object)

In [65]:
dx_llama_3_2.iloc[0]["questions"]

array(['What causes air glow in the atmosphere?',
       'What are the colors of the rainbow airglow? Where do they originate from?',
       'What is the significance of the central band in the image? Is it related to the Milky Way Galaxy?',
       'How was the featured image taken? What were the conditions required for the best capture?',
       'What is airglow generally? Is it always visible?',
       'How do gravity waves affect the atmosphere and airglow?',
       'Why do OH molecules glow red in the airglow?',
       'What is the relationship between airglow and sodium atoms?',
       'Can you explain the visibility of M31, the Andromeda Galaxy in this image?',
       'What was the primary capture method used for the featured image?',
       'How long did it take to expose the image?'], dtype=object)

In [76]:
dx_gpt_4o_mini.iloc[0]["context"]

array(["Why would the sky glow like a giant repeating rainbow? Airglow. Now air glows all of the time, but it is usually hard to see. A disturbance however -- like an approaching storm -- may cause noticeable rippling in the Earth's atmosphere. These gravity waves are oscillations in air analogous to those created when a rock is thrown in calm water.",
       'The deep red glow likely originates from OH molecules about 87-kilometers high, excited by ultraviolet light from the Sun.',
       'The orange and green airglow is likely caused by sodium and oxygen atoms slightly higher up.',
       'The featured image was captured during a climb up Mount Pico in the Azores of Portugal.',
       'A spectacular sky is visible through this banded airglow, with the central band of our Milky Way Galaxy running up the image center, and M31, the Andromeda Galaxy, visible near the top left.',
       "A disturbance however -- like an approaching storm -- may cause noticeable rippling in the Earth's atmosphere.",
       'These gravity waves are oscillations in air analogous to those created when a rock is thrown in calm water.',
       'The long-duration exposure nearly along the vertical walls of airglow likely made the undulating structure particularly visible.',
       'Ground lights originate from the island of Faial in the Atlantic Ocean.',
       'Authors & editors: Robert Nemiroff (MTU) & Jerry Bonnell (UMCP).'],
      dtype=object)

In [77]:
dx_gpt_4o_mini.iloc[0]["search_terms"]

array(['rainbow airglow phenomena', 'causes of airglow',
       'deep red glow in atmosphere', 'sodium and oxygen airglow',
       'Mount Pico Azores photography', 'visible galaxies in airglow',
       "gravity waves in Earth's atmosphere",
       'impact of storms on airglow',
       'photography techniques for airglow',
       'Astronomy Picture of the Day April 18 2021'], dtype=object)

In [39]:
dx.iloc[0]["text"]

"APOD: 2021 April 18 - Rainbow Airglow over the Azores\nAstronomy Picture of the Day\nDiscover the cosmos! Each day a different image or photograph of our fascinating universe is featured, along with a brief explanation written by a professional astronomer.\n2021 April 18\nRainbow Airglow over the Azores Image Credit & Copyright: Miguel Claro ( TWAN ); Rollover Annotation: Judy Schmidt\nExplanation: Why would the sky glow like a giant repeating rainbow? Airglow . Now air glows all of the time, but it is usually hard to see. A disturbance however -- like an approaching storm -- may cause noticeable rippling in the Earth's atmosphere . These gravity waves are oscillations in air analogous to those created when a rock is thrown in calm water . The long-duration exposure nearly along the vertical walls of airglow likely made the undulating structure particularly visible. OK, but where do the colors originate? The deep red glow likely originates from OH molecules about 87-kilometers high, excited by ultraviolet light from the Sun. The orange and green airglow is likely caused by sodium and oxygen atoms slightly higher up. The featured image was captured during a climb up Mount Pico in the Azores of Portugal . Ground lights originate from the island of Faial in the Atlantic Ocean . A spectacular sky is visible through this banded airglow, with the central band of our Milky Way Galaxy running up the image center, and M31, the Andromeda Galaxy , visible near the top left.\nExplore Your Universe: Random APOD Generator Tomorrow's picture: infrared galactic center\n< | Archive | Submissions | Index | Search | Calendar | RSS | Education | About APOD | Discuss | >\nAuthors & editors: Robert Nemiroff ( MTU ) & Jerry Bonnell ( UMCP ) NASA Official: Phillip Newman Specific rights apply . NASA Web Privacy Policy and Important Notices A service of: ASD at NASA / GSFC & Michigan Tech. U.\nAPOD: 2021 April 18 - Rainbow Airglow over the Azores"

In [ ]:
# for gpt-4o-mini
avg_request_tokens = 1065
avg_response_tokens = 517	  # this is from 10k question and answers 
avg_time_taken = 10

# cost per datapoint in sde
cost_per_million_input_tokens = 0.6
cost_per_million_output_tokens = 2.4


cost_per_datapoint = (cost_per_million_input_tokens / 1_000_000) * avg_request_tokens + (cost_per_million_output_tokens / 1_000_000) * avg_response_tokens
cost_per_datapoint*10000

(18.798000000000002, 27.77777777777778)

In [5]:
request_tokens = 1.064292e+07
response_tokens = 5.159565e+06

# for gpt-4o-mini api cost
cost_per_million_input_tokens = 0.6
cost_per_million_output_tokens = 2.4

total_cost = (cost_per_million_input_tokens / 1_000_000) * request_tokens + (cost_per_million_output_tokens / 1_000_000) * response_tokens

total_cost/10_000 # $18.8

0.0018768708

In [45]:
# for gpt-4.1-mini

avg_request_tokens = 1200
avg_response_tokens = 800	  # this is for 10 question and answers only
avg_time_taken = 15

# cost per datapoint in sde
cost_per_million_input_tokens = 0.1
cost_per_million_output_tokens = 1.6


cost_per_datapoint = (cost_per_million_input_tokens / 1_000_000) * avg_request_tokens + (cost_per_million_output_tokens / 1_000_000) * avg_response_tokens
cost_per_datapoint * 10000, avg_time_taken * 10000 / (60 * 60)

(14.000000000000002, 41.666666666666664)

In [79]:
dx_llama_3_2

,id,url1,title,text,prob_included,questions,context,search_terms,request_tokens,response_tokens,total_tokens,time_taken
2846,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210418.html,APOD: 2021 April 18 - Rainbow Airglow over the...,APOD: 2021 April 18 - Rainbow Airglow over the...,0.999830,"[What causes air glow in the atmosphere?, What...","[Airglow . Now air glows all of the time, but ...","[mRNA vaccine side effects, protein folding ac...",1291.0,798.0,2089.0,119.933377
3347,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap221011.html,"APOD: 2022 October 11 - Stars, Dust, Pillars, ...","APOD: 2022 October 11 - Stars, Dust, Pillars, ...",0.999830,[],[],[],NaN,NaN,NaN,NaN
1288,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap160322.html,APOD: 2016 March 22 - Rainbow Airglow over the...,APOD: 2016 March 22 - Rainbow Airglow over the...,0.999829,[What causes airglow and how do gravity waves ...,"[Airglow . Now air glows all of the time, but ...","[mtn cloud formations azores, Milky Way Azores...",1290.0,729.0,2019.0,80.120929
976,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap150422.html,APOD: 2015 April 22 - Colorful Star Clouds in ...,APOD: 2015 April 22 - Colorful Star Clouds in ...,0.999828,"[What is the Gamma Cygni nebula?, How do stars...","[The Gamma Cygni nebula which lies about 1,800...","[Gamma Cygni nebula, Star forming region, Refl...",6566.0,2309.0,8875.0,238.311950
2767,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210125.html,APOD: 2021 January 25 - Southern Cross over Ch...,APOD: 2021 January 25 - Southern Cross over Ch...,0.999828,[What is the significance of the Southern Cros...,[The Southern Cross asterism dominates the Cru...,"[mRNA vaccine side effects, protein folding ac...",1301.0,674.0,1975.0,76.009761

In [7]:

dx_gpt_4o_mini.tail()

,id,url1,title,text,prob_included,questions,context,search_terms,request_tokens,response_tokens,total_tokens,time_taken
225641,/SDE/NASA_Earth_Observatory/|https://earthobse...,https://earthobservatory.nasa.gov/images/14215...,Dust Plumes Off North Africa Coast November 14...,Dust Plumes Off North Africa Coast\nDust and H...,0.999791,[What natural phenomenon was observed flowing ...,[Streamers of dust flow out over the blue wate...,"[North African dust plumes, Mediterranean Sea ...",1029.0,578.0,1607.0,10.181799
127904,/SDE/nasa_science/|https://science.nasa.gov/re...,https://science.nasa.gov/resource/sol-2994-rig...,"Sol 2994: Right Navigation Camera, Cylindrical...","Sol 2994: Right Navigation Camera, Cylindrical...",0.999791,[What did the Curiosity rover create using the...,[NASA's Mars rover Curiosity took 29 images in...,"[Curiosity rover mosaic creation, Mars Curiosi...",1300.0,529.0,1829.0,13.256710
229260,/SDE/NASA_Earth_Observatory/|https://earthobse...,https://earthobservatory.nasa.gov/images/17685...,"Haze along the Himalaya November 28, 2006",Haze along the Himalaya\nDust and Haze\nSea an...,0.999791,[What atmospheric condition contributed to tra...,[Atmospheric pressure could be responsible for...,"[haze in the Himalayas, MODIS satellite imager...",1089.0,489.0,1578.0,10.243371
32105,/SDE/astrobiology_at_nasa/|https://astrobiolog...,https://astrobiology.nasa.gov/nai/directory/ol...,| NASA Astrobiology Institute,| NASA Astrobiology Institute\nNotice: This is...,0.999791,"[What type of research tool is Micro*scope?, W...",[Micro*scope (http://www.mbl.edu/microscope) -...,"[microbial diversity research tools, NASA Astr...",945.0,475.0,1420.0,7.999155
271214,/SDE/NASA_Earth_Observatory/|https://earthobse...,https://earthobservatory.nasa.gov/images/20350...,"Dust Storm over the Persian Gulf August 14, 2008",Dust Storm over the Persian Gulf\nDust and Haz...,0.999791,[What caused the dust storm over the Persian G...,[A dust storm blew over the Persian Gulf in mi...,"[Persian Gulf dust storm 2008, NASA MODIS Terr...",1061.0,642.0,1703.0,10.848794

In [ ]:
# dx_gpt_4o_mini.to_parquet("qa_dataset_gpt_4o_mini_10k_sample.parquet")

In [14]:
dx_gpt_4o_mini.head()

,id,url1,title,text,prob_included,questions,context,search_terms,request_tokens,response_tokens,total_tokens,time_taken
2846,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210418.html,APOD: 2021 April 18 - Rainbow Airglow over the...,APOD: 2021 April 18 - Rainbow Airglow over the...,0.999830,[What causes the sky to glow in the phenomenon...,"[Airglow. Now air glows all of the time, but i...","[airglow phenomenon, gravity waves in atmosphe...",1050.0,615.0,1665.0,10.073934
3347,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap221011.html,"APOD: 2022 October 11 - Stars, Dust, Pillars, ...","APOD: 2022 October 11 - Stars, Dust, Pillars, ...",0.999830,[What structures are found within the Pelican ...,"[On the whole, the nebula appears like a bird ...","[Pelican Nebula structure, Herbig-Haro jets ef...",1055.0,625.0,1680.0,10.069554
1288,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap160322.html,APOD: 2016 March 22 - Rainbow Airglow over the...,APOD: 2016 March 22 - Rainbow Airglow over the...,0.999829,[What causes airglow in the Earth's atmosphere...,"[Airglow . Now air glows all of the time, but ...","[airglow phenomena, colors of airglow, gravity...",1049.0,580.0,1629.0,9.792861
976,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap150422.html,APOD: 2015 April 22 - Colorful Star Clouds in ...,APOD: 2015 April 22 - Colorful Star Clouds in ...,0.999828,"[What is the primary subject of the April 22, ...",[Discover the cosmos! Each day a different ima...,"[star forming region Cygnus, Gamma Cygni nebul...",1012.0,417.0,1429.0,6.736070
2767,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210125.html,APOD: 2021 January 25 - Southern Cross over Ch...,APOD: 2021 January 25 - Southern Cross over Ch...,0.999828,[What astronomical feature is depicted in the ...,[The featured image was taken last month in Ch...,"[Southern Cross visibility, Villarrica volcano...",1058.0,558.0,1616.0,8.383144

In [15]:
# Function to pretty-print the list for Excel
def pretty_print_list_for_excel(item_list):
    if isinstance(item_list, list):
        # 1. Convert the list to its string representation (e.g., "['apple', 'banana']")
        list_str = str(item_list)

        # 2. Insert newlines for better readability
        # Replace ', ' with ',\n'
        # Handle the opening bracket by adding a newline after it if desired
        # You might also want to remove the outer brackets if they're redundant
        
        # Option A: Simple newline after comma (most common and clean)
        formatted_str = list_str.replace(', ', ',\n ')
        
        # Option B: Add a newline after the opening bracket too (more verbose)
        # formatted_str = list_str.replace('[', '[\n ').replace(', ', ',\n ')
        
        return formatted_str
    return item_list # Return as is if not a list


dx_gpt_4o_mini['questions'] = dx_gpt_4o_mini['questions'].apply(pretty_print_list_for_excel)
dx_gpt_4o_mini['context'] = dx_gpt_4o_mini['context'].apply(pretty_print_list_for_excel)
dx_gpt_4o_mini['search_terms'] = dx_gpt_4o_mini['search_terms'].apply(pretty_print_list_for_excel)

In [16]:
dx_gpt_4o_mini.to_excel("qa_dataset_gpt_4o_mini_10k_sample.xlsx", index=False)