In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
column_alias_map = {
    'sourcestr1': 'agency',
    'sourcestr2': 'repository',
    'sourcestr3': 'mission',
    'sourcestr4': 'dataformat',
    'sourcestr5': 'data_process_level',
    'sourcestr6': 'data_process_level_desc',
    'sourcestr7': 'spatial_bounds_coord_sys',
    'sourcestr12': 'urls',
    'sourcestr13': 'scientific_focus',
    'sourcestr14': 'operation_wav_spectral',
    'sourcestr15': 'data_product_desc',
    'sourcestr16': 'investigation',
    'sourcestr17': 'platform',
    'sourcestr19': 'persistent_id',
    'sourcestr20': 'instrument',
    'sourcevarchar2': 'spatial_bounds',
    'sourcestr21': 'spatial_bounds_1',
    'sourcestr22': 'spatial_bounds_2',
    'sourcevarchar10': 'temporal_bounds',
    'sourcedatetime1': 'temporal_bounds_1',
    'sourcedatetime2': 'temporal_bounds_2',
    'sourcedatetime3': 'temporal_bounds_3',
    'sourcedatetime4': 'temporal_bounds_4',
    'sourcedatetime5': 'temporal_bounds_5',
    'sourcevarchar5': 'spatial_resolution_spatial_extent',
    'sourcevarchar6': 'spatial_resolution_spatial_info',
    'sourcestr23': 'spatial_resolution_spatial_info_1',
    'sourcestr24': 'spatial_resolution_spatial_info_2',
    'sourcestr25': 'spatial_resolution_spatial_info_3',
    'sourcestr26': 'spatial_resolution_spatial_info_4',
    'sourcestr27': 'spatial_resolution_spatial_info_5',
    'sourcestr28': 'spatial_resolution_spatial_info_6',
    'sourcestr29': 'data_item_title',
    'sourcestr30': 'temporal_resolution_temp_keywords',
    'sourcevarchar7': 'temporal_resolution_temp_extents',
    'sourcestr31': 'temporal_resolution_1',
    'sourcestr32': 'temporal_resolution_2',
    'sourcestr33': 'temporal_resolution_3',
    'sourcestr34': 'temporal_resolution_4',
    'sourcestr35': 'temporal_resolution_5',
    'sourcestr36': 'data_prod_version',
    'sourcestr37': 'pds_bundle',
    'sourcestr38': 'pds_collection',
    'sourcestr39': 'spase_observed_region',
    'sourcestr40': 'pds_lid',
    'sourcestr41': 'version_num',
    'sourcestr42': 'version_desc',
    'sourcestr43': 'ivo_id',
    'sourcestr44': 'cap_type',
    'sourcestr45': 'ej_desc_simp',
    'sourcestr46': 'ej_geographic_coverage',
    'sourcestr47': 'ej_latency',
    'sourcestr48': 'ej_project',
    'sourcestr49': 'ej_strengths',
    'sourcestr50': 'ej_limitations',
    'sourcestr51': 'ej_data_visualization',
    'sourcestr52': 'ej_intended_use',
    'sourcecsv14': 'ej_indicators',
    'sourcecsv5': 'scientific_keywords_1',
    'sourcecsv6': 'scientific_keywords_2',
    'sourcecsv7': 'scientific_keywords_3',
    'sourcecsv8': 'scientific_keywords_4',
    'sourcecsv9': 'scientific_keywords_5',
    'sourcecsv10': 'scientific_keywords_6',
    'sourcecsv11': 'scientific_keywords_7',
    'sourcecsv12': 'cmr_phenomena',
    'sourcecsv13': 'cmr_measurement_tech',
    'sourcevarchar11': 'data_volume',
    'sourcevarchar12': 'access_constraints',
    'sourcevarchar13': 'use_constraints',
    'sourcevarchar14': 'spase_parameter',
    'sourcevarchar15': 'repos_links',
    'sourcecsv1': 'related_urls_1',
    'sourcecsv2': 'related_urls_2',
    'sourcecsv3': 'related_urls_3',
    'sourcecsv4': 'related_urls_4',
    'sourcebool1': 'IsMetadataViewer',
    'url1': 'download_url',
    'sourcestr8': 'bps_osdr_id',
    'sourcestr9': 'bps_factor',
    'sourcestr10': 'bps_organism',
    'sourcestr11': 'bps_funding',
    'url2': 'ej_sde_link',
    'sourcecsv15': 'coord',
    'sourcestr58': 'coord_unit',
    'sourcedouble1': 'mean_wavel',
    'sourcestr59': 'wavel_unit',
    'sourcestr60': 'frm_name',
    'sourcebool2': 'h_flag',
    'sourcestr61': 'pub_date',
    'sourcestr62': 'contact'
}

# exploring dump

In [ ]:
# CMR

In [ ]:
import pandas as pd


df = pd.read_csv("/rhome/sawale/indus_traning/sentense_transformers/data/api_data/processed_dev_sde_index_api_dump_2025-06-19.csv")

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
compulsory_columns = []
for c in df.columns:
    if (df[c].isna().sum() == 0):
        compulsory_columns.append(c)

In [ ]:
compulsory_columns

In [ ]:
df.iloc[0:2].to_json()

In [ ]:
df.columns

In [ ]:
# df[["sourcestr4"]].value_counts()


for cname in df.columns:
    cname = "sourcestr6"
    x = df[df[cname].str.contains("Mars", case=False, na=False)][[cname]]

    if x.shape[0] > 0:
        print(f"Column: {cname}, Count: {x.shape[0]}")
        print(x.head(10))
        print("\n\n")

In [ ]:
cols = ["id", "url1", "title", "sourcestr15", "sourcestr56", "treepath", "sourcecsv1", "sourcecsv2", "sourcecsv3", "sourcecsv4"]


# interseting field in df
# sourcestr15, title, sourcestr56, treepath, sourcestr44, authors

In [ ]:
cmr = df[df["treepath"] == "/Earth Science/Earth Science Data (CMR)/"][cols]

cmr.head()

In [ ]:
cmr.iloc[0]["url1"]

In [ ]:
cmr.columns

In [ ]:
df.head()

In [ ]:
cmr["url1"].isna().sum()

In [ ]:
pds = df[df["treepath"].str.contains("PDS", na=False)]

pd.set_option('display.max_columns', None)

In [ ]:
pds

# interesting fileds in pds

In [ ]:
pds[cols]["sourcestr15"].isna().sum()

In [ ]:
pds["sourcecsv1"].iloc[0]

In [ ]:
df["sourcestr13"].value_counts()

# for pds

In [4]:
import pandas as pd
df = pd.read_csv("/rhome/sawale/indus_traning/sentense_transformers/data/api_data/processed_dev_sde_index_api_dump_2025-06-19.csv")
pds = df[df["treepath"].str.contains("PDS", na=False)]

pds_cols = [
    "id", 
    "sourcestr13", 
    "sourcecsv5", 
    "sourcestr15", 
    "sourcestr16", 
    "sourcestr17",
    "sourcestr20", 
    "title", 
    "treepath", 
    "sourcestr40", 
    "sourcestr37",
    "sourcestr2",
]


pds_cols_alias = {c:column_alias_map.get(c,c) for c in pds_cols}

pds.rename(columns=pds_cols_alias, inplace=True)

for c in pds_cols_alias.values():
    print(f"Column: {c}, Count: {pds[c].isna().sum()}")
    

pds.rename(columns=pds_cols_alias, inplace=True)

# pds = pds[pds_cols_alias.values()]

/tmp/ipykernel_2317282/3088443693.py:2: DtypeWarning: Columns (3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,25,28,29,30,31,32,33,34,35,36,37,38,39,40,41,43,44,45,46,47,48,49,50,51,53,54,56,57,58,59,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,81,82,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/rhome/sawale/indus_traning/sentense_transformers/data/api_data/processed_dev_sde_index_api_dump_2025-06-19.csv")

Column: id, Count: 0
Column: scientific_focus, Count: 0
Column: scientific_keywords_1, Count: 7637
Column: data_product_desc, Count: 910
Column: investigation, Count: 756
Column: platform, Count: 2315
Column: instrument, Count: 701
Column: title, Count: 0
Column: treepath, Count: 0
Column: pds_lid, Count: 725
Column: pds_bundle, Count: 2851
Column: repository, Count: 3517

/tmp/ipykernel_2317282/3088443693.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pds.rename(columns=pds_cols_alias, inplace=True)
/tmp/ipykernel_2317282/3088443693.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pds.rename(columns=pds_cols_alias, inplace=True)

In [5]:
pds.head()

,id,version,sourcebool1,sourcestr1,repository,sourcestr3,sourcestr4,sourcestr5,sourcestr6,sourcestr7,...,sourcestr44,sourcestr43,sourcecsv15,sourcestr58,sourcedouble1,sourcestr59,authors,sourcebool2,sourcestr60,sourcestr61
31766,/SDE/PDS4_API/|urn:nasa:pds:lab.hydrocarbon_sp...,8f4dcd07495f78b612685e3dec45e394,True,NASA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN
31767,/SDE/PDS4_API/|urn:nasa:pds:mars2020_moxie::1.1,9a0f1ebdc97c2b5d88b4e536fdb9804f,True,NASA,NaN,https://pds.mcp.nasa.gov/api/search/1/products...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN
31768,/SDE/PDS4_API/|urn:nasa:pds:eldorado_nv_dd_ptv...,1ae56cb54e630e1a54a6122d03887a3f,True,NASA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN
31769,/SDE/PDS4_API/|urn:nasa:pds:insight_edl::1.0,a344da3b16a306f7e9f045f3d7287df4,True,NASA,NaN,https://pds.mcp.nasa.gov/api/search/1/products...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN
31770,/SDE/PDS4_API/|urn:nasa:pds:mcmath-pierce_merc...,5b41d8aaa4574f84efbcc94ac9d43d71,True,NASA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN

In [87]:
pds["repository"].value_counts()

repository
Small Bodies                                     3952
Geosciences                                      1143
planetary plasma interactions                     482
Planetary Atmospheres                             265
Imaging                                           254
geosciences                                       155
Planetary Plasma Interactions                      65
Planetary Rings                                    28
Navigation and Ancillary Information Facility      18
Planetary Science Archive                          17
small bodies                                       11
navigation and ancillary information facility       9
Engineering                                         2
Geosciences;Radio Science                           1
Planetary Atmospheres;Small Bodies                  1
Name: count, dtype: int64

In [73]:
pds[pds["sourcestr2"] == "Geosciences;Radio Science"]

,id,version,sourcebool1,sourcestr1,sourcestr2,sourcestr3,sourcestr4,sourcestr5,sourcestr6,sourcestr7,sourcevarchar2,sourcestr21,sourcestr22,sourcevarchar10,sourcedatetime1,sourcedatetime2,sourcedatetime3,sourcedatetime4,sourcedatetime5,sourcevarchar6,sourcevarchar5,sourcestr23,sourcestr24,sourcestr25,sourcestr26,sourcestr27,sourcestr28,sourcevarchar7,sourcestr30,sourcestr31,sourcestr32,sourcestr33,sourcestr34,sourcestr14,scientific_focus,scientific_keywords_1,sourcecsv6,sourcecsv7,sourcecsv8,sourcecsv9,sourcecsv10,sourcecsv11,data_product_desc,investigation,platform,instrument,sourcestr19,sourcestr12,sourcecsv1,sourcevarchar11,sourcevarchar12,sourcevarchar13,title,sourcecsv12,sourcecsv13,sourcestr56,sourcestr41,sourcestr42,sourcevarchar15,sourcestr36,treepath,pds_lid,pds_bundle,sourcestr38,modified,sourcecsv2,sourcecsv3,sourcestr8,sourcestr9,sourcestr10,sourcestr11,doctype,url1,sourcecsv4,sourcevarchar14,sourcestr39,sourcestr44,sourcestr43,sourcecsv15,sourcestr58,sourcedouble1,sourcestr59,authors,sourcebool2,sourcestr60,sourcestr61
34621,/SDE/PDS_API_Legacy_All/|d531fc6c82ffd2f6de629ded26ed1839,53ef5eb29569f85679a5ff081335793a,True,NASA,Geosciences;Radio Science,"https://pds.nasa.gov/ds-view/pds/viewMissionProfile.jsp?MISSION_NAME=""MAGELLAN""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planetary Science,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Calibrated data from three orbits of S-Band (13 cm wavelength) Magellan bistatic radar data collected with NASA antenna DSS 63 on 5 June 1994 when the specular point crossed Maxwell Montes. Similarly processed data were used by Pettengill et al. (SCIENCE, 272, 1628-1631, 1996) to infer existence of a semiconductor layer covering anomalously reflecting regions at high altitude on Venus. This new data set includes calibrated time samples of receiver output as well as calibrated power spectra and voltage cross spectra (between the two received polarizations). The data set was written to three DVD+R volumes for delivery to the NASA Planetary Data System (PDS).",MAGELLAN,MAGELLAN,RADIO SCIENCE SUBSYSTEM,NaN,NaN,NaN,NaN,NaN,NaN,MAGELLAN BISTATIC RADAR CALIBRATED DATA V1.0,NaN,NaN,Data,NaN,NaN,NaN,NaN,/Planetary Science/Planetary Science Data (PDS)/Geosciences Node/Radio Science/,urn:nasa:pds:context_pds3:data_set:data_set.mgn-v-rss-4-bsr-v1.0;urn:nasa:pds:context_pds3:data_set:data_set.mgn-v-rss-4-bsr-v1.0::1.0,context_pds3,data_set,2016-10-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN

In [57]:
pds[pds_cols_alias.values()].head()

,id,scientific_focus,scientific_keywords_1,data_product_desc,investigation,platform,instrument,title,treepath,pds_lid,pds_bundle
31766,/SDE/PDS4_API/|urn:nasa:pds:lab.hydrocarbon_spectra::1.1,Planetary Science,Laboratory Analog Jupiter;Laboratory Analog Saturn;Laboratory Analog Titan;Laboratory Analog,________,Cross Section IR Spectroscopy of Hydrocarbons in Planetary Atmospheres : Individual Investigation,Australian Synchrotron Facility;Canadian Light Source Facility;Old Dominion University Fourier Transform Infrared Spectrometer Laboratory,Bruker IFS 125HR Fourier Transform Spectrometer;Terahertz Far-Infrared Beamline at the Australian Synchrotron Facility;Far-Infrared Beamline at the Canadian Light Source Facility,Laboratory Study of Hydrocarbon IR Spectra Bundle,/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/,urn:nasa:pds:lab.hydrocarbon_spectra,lab.hydrocarbon_spectra
31767,/SDE/PDS4_API/|urn:nasa:pds:mars2020_moxie::1.1,Planetary Science,Mars;Planet,Bundle for the Mars 2020 Mars In-Situ Resource Utilization (ISRU) Experiment (MOXIE),Mars 2020 : Mission,Mars 2020,Mars Oxygen In-Situ Resource Utilization Experiment,Mars 2020 MOXIE Bundle,/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/,urn:nasa:pds:mars2020_moxie,mars2020_moxie
31768,/SDE/PDS4_API/|urn:nasa:pds:eldorado_nv_dd_ptv::1.0,Planetary Science,Earth;Planet,"Dust devil field campaign in El Dorado Playa, Nevada, USA using automated logger stations",Dust Devil Field Observation Campaign : Field Campaign,NaN,Lorenz Meteorology Station Data Logger,"Dust Devil Field Study in El Dorado Valley, Nevada, Jackson and Lorenz, 2015",/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/,urn:nasa:pds:eldorado_nv_dd_ptv,eldorado_nv_dd_ptv
31769,/SDE/PDS4_API/|urn:nasa:pds:insight_edl::1.0,Planetary Science,Mars;Planet,This PDS4 bundle contains the InSight EDL atmospheric reconstruction,InSight : Mission,NaN,EDL,InSight EDL Bundle,/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/,urn:nasa:pds:insight_edl,insight_edl
31770,/SDE/PDS4_API/|urn:nasa:pds:mcmath-pierce_mercury::1.0,Planetary Science,Mercury;Planet,McMath-Pierce Solar Telescope spectral characterization of Mercury,McMath-Pierce Solar Telescope Spectra of Mercury : Observing Campaign,McMath-Pierce Solar Telescope Facility,Vacuum Spectrograph at McMath-Pierce,KPNO McMath-Pierce Solar Telescope Observations of Mercury Bundle,/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/,urn:nasa:pds:mcmath-pierce_mercury,mcmath-pierce_mercury

In [ ]:
pds.

In [59]:
pd.set_option('display.max_columns', None)
pds.head()

,id,version,sourcebool1,sourcestr1,sourcestr2,sourcestr3,sourcestr4,sourcestr5,sourcestr6,sourcestr7,sourcevarchar2,sourcestr21,sourcestr22,sourcevarchar10,sourcedatetime1,sourcedatetime2,sourcedatetime3,sourcedatetime4,sourcedatetime5,sourcevarchar6,sourcevarchar5,sourcestr23,sourcestr24,sourcestr25,sourcestr26,sourcestr27,sourcestr28,sourcevarchar7,sourcestr30,sourcestr31,sourcestr32,sourcestr33,sourcestr34,sourcestr14,scientific_focus,scientific_keywords_1,sourcecsv6,sourcecsv7,sourcecsv8,sourcecsv9,sourcecsv10,sourcecsv11,data_product_desc,investigation,platform,instrument,sourcestr19,sourcestr12,sourcecsv1,sourcevarchar11,sourcevarchar12,sourcevarchar13,title,sourcecsv12,sourcecsv13,sourcestr56,sourcestr41,sourcestr42,sourcevarchar15,sourcestr36,treepath,pds_lid,pds_bundle,sourcestr38,modified,sourcecsv2,sourcecsv3,sourcestr8,sourcestr9,sourcestr10,sourcestr11,doctype,url1,sourcecsv4,sourcevarchar14,sourcestr39,sourcestr44,sourcestr43,sourcecsv15,sourcestr58,sourcedouble1,sourcestr59,authors,sourcebool2,sourcestr60,sourcestr61
31766,/SDE/PDS4_API/|urn:nasa:pds:lab.hydrocarbon_spectra::1.1,8f4dcd07495f78b612685e3dec45e394,True,NASA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 00:00:00,2021-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planetary Science,Laboratory Analog Jupiter;Laboratory Analog Saturn;Laboratory Analog Titan;Laboratory Analog,NaN,NaN,NaN,NaN,NaN,NaN,________,Cross Section IR Spectroscopy of Hydrocarbons in Planetary Atmospheres : Individual Investigation,Australian Synchrotron Facility;Canadian Light Source Facility;Old Dominion University Fourier Transform Infrared Spectrometer Laboratory,Bruker IFS 125HR Fourier Transform Spectrometer;Terahertz Far-Infrared Beamline at the Australian Synchrotron Facility;Far-Infrared Beamline at the Canadian Light Source Facility,NaN,NaN,https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/lab.hydrocarbon_spectra/bundle.lab.hydrocarbon_spectra.xml,NaN,NaN,NaN,Laboratory Study of Hydrocarbon IR Spectra Bundle,NaN,NaN,Data,1.1,NaN,NaN,NaN,/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/,urn:nasa:pds:lab.hydrocarbon_spectra,lab.hydrocarbon_spectra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN
31767,/SDE/PDS4_API/|urn:nasa:pds:mars2020_moxie::1.1,9a0f1ebdc97c2b5d88b4e536fdb9804f,True,NASA,NaN,https://pds.mcp.nasa.gov/api/search/1/products/urn:nasa:pds:context:investigation:mission.mars2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-02-22 20:31:10,2021-08-18 04:41:17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planetary Science,Mars;Planet,NaN,NaN,NaN,NaN,NaN,NaN,Bundle for the Mars 2020 Mars In-Situ Resource Utilization (ISRU) Experiment (MOXIE),Mars 2020 : Mission,Mars 2020,Mars Oxygen In-Situ Resource Utilization Experiment,NaN,NaN,https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/Mars2020/moxie_bundle/bundle_moxie.xml,NaN,NaN,NaN,Mars 2020 MOXIE Bundle,NaN,NaN,Data,1.1,NaN,NaN,NaN,/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/,urn:nasa:pds:mars2020_moxie,mars2020_moxie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN
31768,/SDE/PDS4_API/|urn:nasa:pds:eldorado_nv_dd_ptv::1.0,1ae56cb54e630e1a54a6122d03887a3f,True,NASA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-05-21 00:00:00,2013-09-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planetary Science,Earth;Planet,NaN,NaN,NaN,NaN,NaN,NaN,"Dust devil field campaign in El Dorado Playa, Nevada, USA using automated logger stations",Dust Devil Field Observation Campaign : Field Campaign,NaN,Lorenz Meteorology Station Data Logger,10.1002/2014JEE004712,NaN,https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/eldorado_nv_dd_ptv/bundle_eldorado_nv_dd_ptv.xml,NaN,NaN,NaN,"Dust Devil Field Study in El Dorado Valley, Nevada, Jackson and Lorenz, 2015",NaN,NaN,Data,1.0,NaN,NaN,NaN,/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/,urn:nasa:pds:eldorado_nv_dd_ptv,eldorado_nv_dd_ptv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN
31769,/SDE/PDS4_API/|urn:nasa:pds:insight_edl::1.0,a344da3b16a306f7e9f045f3d7287df4,True,NASA,NaN,https://pds.mcp.nasa.gov/api/search/1/products/urn:nasa:pds:context:investigation:mission.insight,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-11-26 19:39:03,2018-11-26 19:42:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planetary Science,Mars;Planet,NaN,NaN,NaN,NaN,NaN,NaN,This PDS4 bundle contains the InSight EDL atmospheric reconstruction,InSight : Mission,NaN,EDL,NaN,NaN,https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/insight_edl_bundle/bundle_insightedl.xml,NaN,NaN,NaN,InSight EDL Bundle,NaN,NaN,Data,1.0,NaN,NaN,NaN,/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/,urn:nasa:pds:insight_edl,insight_edl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN
31770,/SDE/PDS4_API/|urn:nasa:pds:mcmath-pierce_mercury::1.0,5b41d8aaa4574f84efbcc94ac9d43d71,True,NASA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-01-08 00:00:00,2013-04-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planetary Science,Mercury;Planet,NaN,NaN,NaN,NaN,NaN,NaN,McMath-Pierce Solar Telescope spectral characterization of Mercury,McMath-Pierce Solar Telescope Spectra of Mercury : Observing Campaign,McMath-Pierce Solar Telescope Facility,Vacuum Spectrograph at McMath-Pierce,NaN,NaN,https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/mcmath-pierce_mercury/bundle_mcmath-pierce_mercury.xml,NaN,NaN,NaN,KPNO McMath-Pierce Solar Telescope Observations of Mercury Bundle,NaN,NaN,Data,1.0,NaN,NaN,NaN,/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/,urn:nasa:pds:mcmath-pierce_mercury,mcmath-pierce_mercury,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN

# for cmr

In [ ]:
import pandas as pd
import requests
import xmltodict
import logging
from tqdm.auto import tqdm
from typing import List, Dict, Any, Optional
from concurrent.futures import ThreadPoolExecutor, as_completed
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# --- Setup Logging ---
# Configure logging to provide informative output
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# --- Helper Functions ---

def deep_get(d: Dict, keys: List[str]) -> Optional[Any]:
    """
    Safely retrieves a nested value from a dictionary.

    Args:
        d: The dictionary to search.
        keys: A list of keys representing the path to the value.

    Returns:
        The requested value, or None if any key in the path is not found.
    """
    for key in keys:
        if isinstance(d, dict):
            d = d.get(key)
        else:
            return None
    return d

def get_session_with_retries(
    retries: int = 3,
    backoff_factor: float = 0.3,
    status_forcelist: tuple = (500, 502, 503, 504),
    session: Optional[requests.Session] = None,
) -> requests.Session:
    """
    Creates a requests.Session object with a retry mechanism.

    This setup will automatically retry requests that fail due to network errors
    or specific HTTP status codes, with an exponential backoff delay.
    """
    session = session or requests.Session()
    retry_strategy = Retry(
        total=retries,
        read=retries,
        connect=retries,
        backoff_factor=backoff_factor,
        status_forcelist=status_forcelist,
    )
    adapter = HTTPAdapter(max_retries=retry_strategy)
    session.mount('http://', adapter)
    session.mount('https://', adapter)
    return session

# --- Core Logic ---

def get_purpose_from_cmr_xml(url: str, session: requests.Session) -> Optional[List[str]]:
    """
    Fetches a CMR XML from a URL, parses it, and extracts the 'purpose' field(s).

    Args:
        url: The URL of the XML metadata to fetch.
        session: A requests.Session object to use for the HTTP request.

    Returns:
        A list of purpose strings found in the XML, or None if an error occurs.
    """
    try:
        response = session.get(url, timeout=15)  # Set a reasonable timeout
        response.raise_for_status()  # Raise an exception for bad status codes (4xx or 5xx)
        
        xml_content = response.content
        if not xml_content:
            logging.warning(f"Empty content received from URL: {url}")
            return [] # Return empty list for empty content

        xml_dict = xmltodict.parse(xml_content)

        # Safely navigate the nested dictionary structure
        id_info_path = ["gmi:MI_Metadata", "gmd:identificationInfo"]
        identification_info = deep_get(xml_dict, id_info_path)

        if not identification_info:
            logging.warning(f"Could not find 'identificationInfo' in XML from: {url}")
            return []

        # Ensure identification_info is a list to handle single or multiple entries
        if not isinstance(identification_info, list):
            identification_info = [identification_info]

        purposes = []
        purpose_path = ["gmd:MD_DataIdentification", "gmd:purpose", "gco:CharacterString"]
        for item in identification_info:
            purpose = deep_get(item, purpose_path)
            if purpose and isinstance(purpose, str):
                purposes.append(purpose.strip())
        
        return purposes

    except requests.exceptions.RequestException as e:
        logging.error(f"Request failed for URL {url}: {e}")
        return None
    except xmltodict.expat.ExpatError as e:
        logging.error(f"XML parsing failed for URL {url}: {e}")
        return None
    except Exception as e:
        logging.error(f"An unexpected error occurred for URL {url}: {e}")
        return None

def process_urls_concurrently(urls: pd.Series) -> pd.Series:
    """
    Processes a series of URLs concurrently to fetch and parse purposes.

    Args:
        urls: A pandas Series containing the URLs to process.

    Returns:
        A pandas Series containing the lists of purposes for each URL.
    """
    results = [None] * len(urls)
    session = get_session_with_retries()
    
    # Use ThreadPoolExecutor for concurrent I/O-bound tasks
    with ThreadPoolExecutor(max_workers=10) as executor:
        # Create a dictionary to map future objects to their original index
        future_to_index = {executor.submit(get_purpose_from_cmr_xml, url, session): i for i, url in enumerate(urls)}
        
        # Use tqdm to create a progress bar
        pbar = tqdm(total=len(urls), desc="Fetching CMR Purposes")
        
        for future in as_completed(future_to_index):
            index = future_to_index[future]
            try:
                results[index] = future.result()
            except Exception as e:
                # This catches errors from the future.result() call itself
                logging.error(f"Future for URL {urls[index]} generated an exception: {e}")
            pbar.update(1) # Increment the progress bar
        pbar.close()

    return pd.Series(results, index=urls.index)

df = pd.read_csv("/rhome/sawale/indus_traning/sentense_transformers/data/api_data/processed_dev_sde_index_api_dump_2025-06-19.csv")
cmr = df[df["treepath"] == "/Earth Science/Earth Science Data (CMR)/"]


cmr['purposes'] = process_urls_concurrently(cmr['url1'])
cols_to_convert = ['sourcestr25', 'sourcestr28', 'sourcevarchar7', 'sourcestr32', 'sourcestr34']
cmr[cols_to_convert] = cmr[cols_to_convert].astype(str)

cmr.to_parquet("/rhome/sawale/indus_traning/sentense_transformers/data/api_data/cmr_with_purposes.parquet", index=False)

In [3]:
import pandas as pd
# df = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/data/api_data/processed_dev_sde_index_api_dump_2025-06-19.csv")
# cmr = df[df["treepath"] == "/Earth Science/Earth Science Data (CMR)/"]
cmr = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/data/api_data/cmr_with_purposes.parquet")


cmr_cols = [
  "id",
  "url1",
  "treepath",
  "title",
  "sourcestr1",
  "sourcestr15",

  "sourcestr13",
  "sourcecsv5",
  "sourcestr17",
  "sourcestr20",
  "sourcecsv12",
  "sourcestr4",
  "purposes",
]

cmr_cols_alias = {c:column_alias_map.get(c,c) for c in cmr_cols}

cmr.rename(columns=cmr_cols_alias, inplace=True)

for c in cmr_cols_alias.values():
    print(f"Column: {c}, Count: {cmr[c].isna().sum()}")

Column: id, Count: 0
Column: download_url, Count: 0
Column: treepath, Count: 0
Column: title, Count: 0
Column: agency, Count: 0
Column: data_product_desc, Count: 0
Column: scientific_focus, Count: 0
Column: scientific_keywords_1, Count: 0
Column: platform, Count: 0
Column: instrument, Count: 19848
Column: cmr_phenomena, Count: 34178
Column: dataformat, Count: 40653
Column: purposes, Count: 196

In [4]:
cmr.head()

,id,version,sourcebool1,agency,sourcestr2,sourcestr3,dataformat,sourcestr5,sourcestr6,sourcestr7,...,sourcestr43,sourcecsv15,sourcestr58,sourcedouble1,sourcestr59,authors,sourcebool2,sourcestr60,sourcestr61,purposes
0,/SDE/CMR_API/|C2789815280-ENVIDAT,8e1d9ee03ee184ad968df42338eda2f1,True,ENVIDAT,WSL,None,None,Not provided,None,CARTESIAN,...,None,None,None,0.0,None,None,False,None,None,[]
1,/SDE/CMR_API/|C1214305813-AU_AADC,d19a350c0d76c1e1a14db82478a0729c,True,Other,AU/AADC,None,None,Not provided,None,CARTESIAN,...,None,None,None,0.0,None,None,False,None,None,[]
2,/SDE/CMR_API/|C2207472890-FEDEO,17f2528563d2006a1e4f64e15be52bfe,True,Other,VITO,None,None,None,None,CARTESIAN,...,None,None,None,0.0,None,None,False,None,None,[]
3,/SDE/CMR_API/|C1214313574-AU_AADC,2b5891eef9a36061eed689afaf531eef,True,Other,AU/AADC,None,None,Not provided,None,CARTESIAN,...,None,None,None,0.0,None,None,False,None,None,[]
4,/SDE/CMR_API/|C1214305884-AU_AADC,926ea98668b976a7ee8da96a769d3415,True,Other,AU/AADC,None,None,Not provided,None,CARTESIAN,...,None,None,None,0.0,None,None,False,None,None,[]

In [4]:
# cmr["purposes"].value_counts()

cmr["purposes"] = cmr["purposes"].apply(lambda x: " ".join(x) if x is not None else None)
cmr["purposes"] = cmr["purposes"].apply(lambda x: x.strip() if isinstance(x, str) and len(x.strip()) > 0 else None)
cmr["purposes"].value_counts()

purposes
This dataset is available to the public for a wide variety of uses including scientific research and analysis.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        11408
Tree ring data from the International Tree Ring Data Bank and World Data Center for Paleoclimatology archives. Most data sets include raw treering measurements (most are annual ring width, with some collections of earlywood or latewood width or wood density), plus chronologies (standardized growth indices for a site compiled from multiple treering samples). Reconstructions of climate variables are included with some of these data sets.  Each data type is stored in a separate data file; the data type is coded into the file name. For details please see: http://www.ncdc.noaa.gov/paleo/treeinfo.html                                                                                                                                                                                                                                                             4761
Scientific Research                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1488
Records of past temperature derived from boreholes drilled into the Earth crust. Parameter keywords describe what was measured in this dataset. Additional summary information can be found in the abstracts of papers listed in the dataset citations. Information on the University of Michigan Borehole Database datasets are found on the Borehole Data Page (http://www.ncdc.noaa.gov/paleo/borehole).                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1014
Science Research                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        922
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...
This dataset provides the basis for analysis of precipitation means and variations from the global scale to regional scales with a daily time resolution and uses both satellite and in situ precipitation observations.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
This dataset provides scientific researchers a high quality Climate Data Record (CDR) of global precipitation, from the Global Precipitation Climatology Project (GPCP).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
Global Summary of the Month (GSOM) data provides a global summary of meteorological elements (max temp, snow, etc) from 1763 to present with updates weekly on a monthly resolution. The data are computed from input data using the Global Historical Climatology Network (GHCN)-Daily dataset.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
Global Summary of the Year (GSOY) data provides a global summary of meteorological elements (max temp, snow, etc) from 1763 to present with updates weekly on a yearly resolution. The data are computed from input data using the Global Historical Climatology Network (GHCN)-Daily dataset.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
The Biological and Chemical Oceanography Data Management Office (BCO-DMO) was created to serve PIs funded by the NSF. BCO-DMO manages oceanographic scientific research data contributed by the originating principal investigators. The BCO-DMO data system facilitates data stewardship, dissemination, and storage. The main BCO-DMO objective is to support the scientific community through improved access to ocean science data.\n\nU.S. GLOBEC (GLOBal Ocean ECosystems Dynamics) is a multi-disciplinary research program designed by oceanographers, fishery scientists, and marine ecologists to examine the potential impact of global climate change on ocean ecosystems. The objective of U.S. GLOBEC studies on Georges Bank is to understand how changes in environmental conditions affect the dynamics of the target copepod and fish (cod and haddock) species.        1
Name: count, Length: 3172, dtype: int64

In [5]:
cmr["dataformat"].value_counts()

dataformat
netCDF-4                                                                  1707
ASCII                                                                     1353
HDF-EOS2                                                                   637
multiple                                                                   571
HDF-EOS5                                                                   541
                                                                          ...
txt.                                                                         1
XML;GeoTIFF;CSV;ASCII                                                        1
XML;GeoTIFF;CSV                                                              1
GIS Layers                                                                   1
ArcInfo export format;shapefile (Polygons Only);shapefile (Lines Only)       1
Name: count, Length: 1218, dtype: int64

In [ ]:
pd.set_option('display.max_colwidth', None)
# cmr[["scientific_keywords_1", "scientific_keywords_2", "scientific_keywords_3", "scientific_keywords_4", "scientific_keywords_5", "scientific_keywords_6"]]
# cmr["cmr_phenomena"].value_counts()

In [ ]:
ccs = []
for c in cmr.columns:
    # 1. Cast the column to string type to ensure .str will work
    # 2. Use na=False to treat any missing values (NaN) as not containing "HLS"
    #    This prevents potential errors or unintended behavior with missing data.
    mask = cmr[c].astype(str).str.contains("HLS", na=False)
    
    # .sum() on a boolean mask is an efficient way to count 'True' values
    count = mask.sum()
    
    if count > 0:
        print(f"Column: {c}, Count: {count}")

In [44]:
pd.set_option('display.max_colwidth', None)
cmr[["cmr_phenomena", "scientific_keywords_1", "title"]].head(10)

,cmr_phenomena,scientific_keywords_1,title
0,FOREST RESERVES;NATIONAL FOREST INVENTORY;NEAR-NATURAL FOREST;SWITZERLAND;TREE MORTALITY,EARTH SCIENCE/FOREST SCIENCE/BIOSPHERE/FOREST CONSERVATION,'Latent reserves' within the Swiss NFI
1,ANTIMONY;ARSENIC;BIOAVAILABLE METALS;CADMIUM;CHROMIUM;COPPER;IRON;KINETICS;LEAD;LOCATION;MANGANESE;MESS;MULTIVARIATE ANALYSIS;NICKEL;PACS;REPLICATE;SILVER;SITE;TIN;WINDMILL ISLANDS;ZINC,EARTH SCIENCE/ENVIRONMENTAL IMPACTS/HUMAN DIMENSIONS/HEAVY METALS CONCENTRATION;EARTH SCIENCE/MARINE SEDIMENTS/OCEANS;EARTH SCIENCE/MARINE SEDIMENTS/OCEANS/SEDIMENT CHEMISTRY,0.5 hour 1 M HCl extraction data for the Windmill Islands marine sediments
2,VEGETATION-1;VEGETATION-2;SPOT;SPOT-4;SPOT-5;Cloud;Radiometric quality;Shadow;Snow;land use,EARTH SCIENCE/CLOUDS/ATMOSPHERE;EARTH SCIENCE/CRYOSPHERIC INDICATORS/CLIMATE INDICATORS/SNOW COVER;EARTH SCIENCE/LAND USE/LAND COVER/LAND SURFACE,10 Days Synthesis of SPOT VEGETATION Images (VGT-S10)
3,ANTARCTICA;CANE;DELTA OXYGEN-18;DENSITY;DEPTH HOAR;DISTANCE;ELEVATION;FIRN;GLACIER;GRAIN SIZE;HEIGHT;ICE CRUSTS;LATITUTDE;LONGITUDE;MASS ACCUMULATION;TEMPERATURE;YEAR,EARTH SCIENCE/GLACIERS/ICE SHEETS/CRYOSPHERE/GLACIERS;EARTH SCIENCE/SNOW/ICE/CRYOSPHERE/SNOW/ICE TEMPERATURE,10 m firn temperature data: LGB traverses 1990-95
4,ANTARCTICA;ORGANOCHLORINES;SEABIRDS;fulmar;Adelie penguin;preenoil;polychlorinated biphenyls;hexachlorobenzene;dieldrin;PCB;HCB;DDE;Pygoscelis adeliae;Fulmarus glacialoides;morphometrics,EARTH SCIENCE/ENVIRONMENTAL IMPACTS/HUMAN DIMENSIONS/CONTAMINANT LEVELS/SPILLS;EARTH SCIENCE/ANIMALS/VERTEBRATES/BIOLOGICAL CLASSIFICATION/BIRDS;EARTH SCIENCE/ANIMALS/VERTEBRATES/BIOLOGICAL CLASSIFICATION;EARTH SCIENCE/ECOLOGICAL DYNAMICS/BIOSPHERE/ECOTOXICOLOGY/SPECIES BIOACCUMULATION;EARTH SCIENCE/ECOLOGICAL DYNAMICS/BIOSPHERE/ECOTOXICOLOGY/TOXICITY LEVELS,10 year trend of levels of organochlorine pollutants in Antarctic seabirds
5,ICP FORESTS;LONG-TERM FOREST ECOSYSTEM RESEARCH;SOIL MOISTURE;SOIL WATER CONTENT;SWISS FOREST LAB,EARTH SCIENCE/ATMOSPHERIC/OCEAN INDICATORS/CLIMATE INDICATORS,10-HS Pfynwald
6,None,EARTH SCIENCE/ATMOSPHERIC PRESSURE/ATMOSPHERE/SURFACE PRESSURE,12 Hourly Interpolated Surface Air Pressure from Buoys
7,HOLOCENE;MACQUARIE ISLAND;WESTERLY WINDS;LAKE SEDIMENT CORERS,EARTH SCIENCE/GEOCHEMISTRY/SOLID EARTH;EARTH SCIENCE/OCEAN/LAKE RECORDS/PALEOCLIMATE/SEDIMENTS;EARTH SCIENCE/PLANTS/BIOLOGICAL CLASSIFICATION/MICROALGAE/DIATOMS;EARTH SCIENCE/OCEAN/LAKE RECORDS/PALEOCLIMATE/RADIOCARBON,"12,000 year record of sea spray and minerogenic input from Emerald Lake, Macquarie Island"
8,None,EARTH SCIENCE/SEA ICE/CRYOSPHERE/SEA ICE MOTION,12-Hourly Interpolated Surface Position from Buoys
9,None,EARTH SCIENCE/SEA ICE/CRYOSPHERE/SEA ICE MOTION,12-Hourly Interpolated Surface Velocity from Buoys

# creating CMR title-description pairs

In [ ]:
# final columns
# query, context, type, synthesized, source, metadata

# current columsn interested
# Column: id, Count: 0
# Column: download_url, Count: 0
# Column: treepath, Count: 0
# Column: title, Count: 0
# Column: data_product_desc, Count: 0
# Column: scientific_keywords_1, Count: 0
# Column: platform, Count: 0
# Column: purposes, Count: 196
# Column: instrument, Count: 19848
# Column: cmr_phenomena, Count: 34178
# Column: dataformat, Count: 40653



# transformations
# query = title

# context = f"""
# if data_product_desc is not Nan or not empty string
#       "Description"
#       {data_product_desc}
# if scientific_keywords_1 is not Nan or not empty string
#     "Scientific Keywords": {scientific_keywords_1}
# if purposes is not Nan or not empty string
#     "Purpose": {purposes}
# if dataformat is not Nan or not empty string
#     "Dataformat": {dataformat}
# if instrument is not Nan or not empty string
#     "Instrument": {instrument}
# if cmr_phenomena is not Nan or not empty string
#     "CMR Phenomena": {cmr_phenomena}
#  """

# synthesized = False

# metadata = {
#     "id": id,
#     "treepath": treepath,
#     "download_url": download_url,
#     "title": title,
#     "agency": agency,
#     "data_product_desc": data_product_desc,
#     "scientific_keywords_1": scientific_keywords_1,
#     "platform": platform,
#     "instrument": instrument,
#     "cmr_phenomena": cmr_phenomena
#     "dataformat": dataformat,
#     "purposes": purposes
# }

In [6]:
import pandas as pd
import numpy as np
import json

def transform_cmr_dataframe(cmr: pd.DataFrame) -> pd.DataFrame:
    """
    Transforms a raw CMR DataFrame into a structured format.

    This updated function vectorizes the creation of the 'context' column for
    improved performance and ensures all specified fields from the original
    request are consistently included in the 'metadata' column.

    Args:
        cmr: The input pandas DataFrame with the source CMR data.

    Returns:
        A new pandas DataFrame with the columns: 'query', 'context',
        'type', 'synthesized', 'source', and 'metadata'.
    """
    # Create a copy to avoid modifying the original DataFrame
    df = cmr.copy()

    # 1. Create the 'query' column from the 'title'
    df['query'] = df['title']

    # 2. Create the 'context' column using a more efficient, vectorized approach
    context_parts = []
    
    # Define the fields and their labels for the context string
    context_fields = {
        'data_product_desc': 'Description',
        'purposes': 'Purpose',
        'scientific_keywords_1': 'Scientific Keywords',
        'cmr_phenomena': 'CMR Phenomena',
        'dataformat': 'Dataformat',
        'instrument': 'Instrument',
        # 'platform': 'Platform',
        # 'agency': 'Agency',
        
    }
    
    for col, label in context_fields.items():
        # Ensure the column exists in the DataFrame
        if col in df.columns:
            # Use np.where for conditional, vectorized string creation
            part = np.where(
                df[col].notna() & (df[col] != ''),
                f"{label}: " + df[col].astype(str),
                '' # Use an empty string if the condition is false
            )
            context_parts.append(pd.Series(part, index=df.index))

    # Join all parts. Concatenate the series and then join non-empty parts with a newline.
    # This avoids leading/trailing/double newlines.
    df['context'] = [
        "\n".join(filter(None, values)) for values in zip(*context_parts)
    ]
    
    # 3. Create the 'synthesized' column
    df['synthesized'] = False
    
    # 4. Create 'type' and 'source' columns with default values
    df['type'] = 'title-description'
    df['source'] = 'CMR'

    # 5. Create the 'metadata' column
    # Define all columns to be included in the metadata JSON for consistency.
    metadata_cols = [
        'id', 'treepath', 'download_url', 'title', 'agency',
        'data_product_desc', 'scientific_keywords_1', 'platform',
        'instrument', 'cmr_phenomena', 'dataformat', 'purposes'
    ]
    
    # Filter out columns that don't exist in the input DataFrame to prevent errors.
    existing_metadata_cols = [col for col in metadata_cols if col in df.columns]

    # Efficiently create a list of dictionaries from the relevant columns.
    metadata_dicts = df[existing_metadata_cols].to_dict(orient='records')
    
    # Convert the list of dictionaries to a Series of JSON strings.
    df['metadata'] = pd.Series(
        [json.dumps(d) for d in metadata_dicts],
        index=df.index
    )

    # 6. Select and order the final columns
    final_columns = ['query', 'context', 'type', 'synthesized', 'source', 'metadata']
    final_df = df[final_columns]
    
    return final_df

cmr_pairs = transform_cmr_dataframe(cmr)

In [7]:
cmr_pairs.head()

,query,context,type,synthesized,source,metadata
0,'Latent reserves' within the Swiss NFI,Description: The files refer to the data used ...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C2789815280-ENVIDAT"", ""t..."
1,0.5 hour 1 M HCl extraction data for the Windm...,Description: These results are for the 0.5 hou...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C1214305813-AU_AADC"", ""t..."
2,10 Days Synthesis of SPOT VEGETATION Images (V...,Description: The VGT-S10 are near-global or co...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C2207472890-FEDEO"", ""tre..."
3,10 m firn temperature data: LGB traverses 1990-95,Description: The Lambert Glacier Basin (LGB) s...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C1214313574-AU_AADC"", ""t..."
4,10 year trend of levels of organochlorine poll...,Description: Metadata record for data from ASA...,title-description,False,CMR,"{""id"": ""/SDE/CMR_API/|C1214305884-AU_AADC"", ""t..."

In [ ]:
cmr_pairs["metadata"]

In [10]:
cmr_pairs.to_parquet("/rhome/sawale/indus_traning/sentense_transformers/data/stage2_sde/cmr_pairs.parquet", index=False)

# creating PDS title-description pairs

In [ ]:
# final columns
# query, context, type, synthesized, source, metadata

# current columsn interested
# Column: id, Count: 0
# Column: scientific_keywords_1, Count: 7637
# Column: data_product_desc, Count: 910
# Column: investigation, Count: 756
# Column: instrument, Count: 701
# Column: title, Count: 0
# Column: treepath, Count: 0
# Column: pds_lid, Count: 725
# Column: repository, Count: 3517

# transformations
# query = title

# context = f"""
# if data_product_desc is not Nan or not empty string
#     "Description" 
#       {data_product_desc}
# if scientific_keywords_1 is not Nan or not empty string
#     "Target": {scientific_keywords_1}
# if repository is not Nan or not empty string
#     "Repository": {repository}
# if investigation is not Nan or not empty string
#     "Investigation": {investigation}
# if instrument is not Nan or not empty string
#     "Instrument": {instrument}
#  """

# synthesized = False

# source = "PDS"

# type = 'title-description

# metadata = {
#     "id": id,
#     "pds_lid": pds_lid
#     "treepath": treepath,
#     "title": title,
#     "data_product_desc": data_product_desc,
#     "scientific_keywords_1": scientific_keywords_1,
#     "repository": repository
#     "instrument": instrument,
#     "platform": platform,
#     "investigation": investigation,
# }

In [6]:
import pandas as pd
import numpy as np
import json


def transform_pds_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Transforms a PDS DataFrame to a specified format with columns:
    query, context, type, synthesized, source, and metadata,
    based on the latest guidelines.

    Args:
        df: The input DataFrame with the source PDS columns.

    Returns:
        A new DataFrame with the transformed data.
    """
    # Create a new DataFrame to hold the transformed data
    final_df = pd.DataFrame()

    # 1. 'query' transformation
    # The guideline specifies 'title' as the source for query,
    # but the current columns list and previous code used 'data_item_title'.
    # Assuming 'title' is the correct new column name to use for 'query'.
    final_df['query'] = df['title']

    # 2. Create the 'context' column using a more efficient, vectorized approach
    context_parts = []
    
    # Define the fields and their labels for the context string
    context_fields = {
        'data_product_desc': 'Description',
        'scientific_keywords_1': 'Target',
        'repository': 'Repository',
        'investigation': 'Investigation',
        'instrument': 'Instrument',
    }

    for col, label in context_fields.items():
        # Ensure the column exists in the DataFrame
        if col in df.columns:
            # Use np.where for conditional, vectorized string creation
            part = np.where(
                df[col].notna() & (df[col] != ''),
                f"{label}: " + df[col].astype(str),
                '' # Use an empty string if the condition is false
            )
            context_parts.append(pd.Series(part, index=df.index))

    # This avoids leading/trailing/double newlines.
    final_df['context'] = [
        "\n".join(filter(None, values)) for values in zip(*context_parts)
    ]

    # 3. 'synthesized' transformation
    final_df['synthesized'] = False
    
    # 4. 'source' transformation
    final_df['source'] = 'PDS'

    # 5. 'type' column (not explicitly defined in new guidelines, keeping a default)
    final_df['type'] = 'title-description' # Assuming a more specific type than 'default'

    # 6. 'metadata' transformation
    metadata_cols = [
        'id', 'pds_lid', 'treepath', 'title', 'data_product_desc',
        'scientific_keywords_1', 'repository', 'instrument',
        'platform', 'investigation'
    ]
    # Filter out columns that don't exist in the input DataFrame to prevent errors.
    existing_metadata_cols = [col for col in metadata_cols if col in df.columns]
    # Efficiently create a list of dictionaries from the relevant columns.
    metadata_dicts = df[existing_metadata_cols].to_dict(orient='records')
    # Convert the list of dictionaries to a Series of JSON strings.
    final_df['metadata'] = pd.Series(
        [json.dumps(d) for d in metadata_dicts],
        index=df.index
    )

    # 6. Select and order the final columns
    final_columns = ['query', 'context', 'type', 'synthesized', 'source', 'metadata']
    final_df = final_df[final_columns]

    return final_df


pds_pairs = transform_pds_data(pds)

In [7]:
pds_pairs.shape

(9920, 6)

In [11]:
# set column width to None
pd.set_option('display.max_colwidth', None)

pds_pairs.head()

,query,context,type,synthesized,source,metadata
31766,Laboratory Study of Hydrocarbon IR Spectra Bundle,Description: ________\nTarget: Laboratory Analog Jupiter;Laboratory Analog Saturn;Laboratory Analog Titan;Laboratory Analog\nInvestigation: Cross Section IR Spectroscopy of Hydrocarbons in Planetary Atmospheres : Individual Investigation\nInstrument: Bruker IFS 125HR Fourier Transform Spectrometer;Terahertz Far-Infrared Beamline at the Australian Synchrotron Facility;Far-Infrared Beamline at the Canadian Light Source Facility,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:lab.hydrocarbon_spectra::1.1"", ""pds_lid"": ""urn:nasa:pds:lab.hydrocarbon_spectra"", ""treepath"": ""/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/"", ""title"": ""Laboratory Study of Hydrocarbon IR Spectra Bundle"", ""data_product_desc"": ""________"", ""scientific_keywords_1"": ""Laboratory Analog Jupiter;Laboratory Analog Saturn;Laboratory Analog Titan;Laboratory Analog"", ""repository"": NaN, ""instrument"": ""Bruker IFS 125HR Fourier Transform Spectrometer;Terahertz Far-Infrared Beamline at the Australian Synchrotron Facility;Far-Infrared Beamline at the Canadian Light Source Facility"", ""platform"": ""Australian Synchrotron Facility;Canadian Light Source Facility;Old Dominion University Fourier Transform Infrared Spectrometer Laboratory"", ""investigation"": ""Cross Section IR Spectroscopy of Hydrocarbons in Planetary Atmospheres : Individual Investigation""}"
31767,Mars 2020 MOXIE Bundle,Description: Bundle for the Mars 2020 Mars In-Situ Resource Utilization (ISRU) Experiment (MOXIE)\nTarget: Mars;Planet\nInvestigation: Mars 2020 : Mission\nInstrument: Mars Oxygen In-Situ Resource Utilization Experiment,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:mars2020_moxie::1.1"", ""pds_lid"": ""urn:nasa:pds:mars2020_moxie"", ""treepath"": ""/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/"", ""title"": ""Mars 2020 MOXIE Bundle"", ""data_product_desc"": ""Bundle for the Mars 2020 Mars In-Situ Resource Utilization (ISRU) Experiment (MOXIE)"", ""scientific_keywords_1"": ""Mars;Planet"", ""repository"": NaN, ""instrument"": ""Mars Oxygen In-Situ Resource Utilization Experiment"", ""platform"": ""Mars 2020"", ""investigation"": ""Mars 2020 : Mission""}"
31768,"Dust Devil Field Study in El Dorado Valley, Nevada, Jackson and Lorenz, 2015","Description: Dust devil field campaign in El Dorado Playa, Nevada, USA using automated logger stations\nTarget: Earth;Planet\nInvestigation: Dust Devil Field Observation Campaign : Field Campaign\nInstrument: Lorenz Meteorology Station Data Logger",title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:eldorado_nv_dd_ptv::1.0"", ""pds_lid"": ""urn:nasa:pds:eldorado_nv_dd_ptv"", ""treepath"": ""/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/"", ""title"": ""Dust Devil Field Study in El Dorado Valley, Nevada, Jackson and Lorenz, 2015"", ""data_product_desc"": ""Dust devil field campaign in El Dorado Playa, Nevada, USA using automated logger stations"", ""scientific_keywords_1"": ""Earth;Planet"", ""repository"": NaN, ""instrument"": ""Lorenz Meteorology Station Data Logger"", ""platform"": NaN, ""investigation"": ""Dust Devil Field Observation Campaign : Field Campaign""}"
31769,InSight EDL Bundle,Description: This PDS4 bundle contains the InSight EDL atmospheric reconstruction\nTarget: Mars;Planet\nInvestigation: InSight : Mission\nInstrument: EDL,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:insight_edl::1.0"", ""pds_lid"": ""urn:nasa:pds:insight_edl"", ""treepath"": ""/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/"", ""title"": ""InSight EDL Bundle"", ""data_product_desc"": ""This PDS4 bundle contains the InSight EDL atmospheric reconstruction"", ""scientific_keywords_1"": ""Mars;Planet"", ""repository"": NaN, ""instrument"": ""EDL"", ""platform"": NaN, ""investigation"": ""InSight : Mission""}"
31770,KPNO McMath-Pierce Solar Telescope Observations of Mercury Bundle,Description: McMath-Pierce Solar Telescope spectral characterization of Mercury\nTarget: Mercury;Planet\nInvestigation: McMath-Pierce Solar Telescope Spectra of Mercury : Observing Campaign\nInstrument: Vacuum Spectrograph at McMath-Pierce,title-description,False,PDS,"{""id"": ""/SDE/PDS4_API/|urn:nasa:pds:mcmath-pierce_mercury::1.0"", ""pds_lid"": ""urn:nasa:pds:mcmath-pierce_mercury"", ""treepath"": ""/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/"", ""title"": ""KPNO McMath-Pierce Solar Telescope Observations of Mercury Bundle"", ""data_product_desc"": ""McMath-Pierce Solar Telescope spectral characterization of Mercury"", ""scientific_keywords_1"": ""Mercury;Planet"", ""repository"": NaN, ""instrument"": ""Vacuum Spectrograph at McMath-Pierce"", ""platform"": ""McMath-Pierce Solar Telescope Facility"", ""investigation"": ""McMath-Pierce Solar Telescope Spectra of Mercury : Observing Campaign""}"

In [10]:
pds_pairs["metadata"].iloc[0]

'{"id": "/SDE/PDS4_API/|urn:nasa:pds:lab.hydrocarbon_spectra::1.1", "pds_lid": "urn:nasa:pds:lab.hydrocarbon_spectra", "treepath": "/Planetary Science/Planetary Science Data (PDS)/Atmospheres Node/", "title": "Laboratory Study of Hydrocarbon IR Spectra Bundle", "data_product_desc": "________", "scientific_keywords_1": "Laboratory Analog Jupiter;Laboratory Analog Saturn;Laboratory Analog Titan;Laboratory Analog", "repository": NaN, "instrument": "Bruker IFS 125HR Fourier Transform Spectrometer;Terahertz Far-Infrared Beamline at the Australian Synchrotron Facility;Far-Infrared Beamline at the Canadian Light Source Facility", "platform": "Australian Synchrotron Facility;Canadian Light Source Facility;Old Dominion University Fourier Transform Infrared Spectrometer Laboratory", "investigation": "Cross Section IR Spectroscopy of Hydrocarbons in Planetary Atmospheres : Individual Investigation"}'