In [1]:
%reload_ext autoreload
%autoreload 2

In [13]:
import pandas as pd

filtered_sde = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/gen_data_stage3/filtered_sde_data/")
original_sde = pd.read_parquet("/rhome/sawale/indus_traning/mlm-fine-tuning/mlm/data/cleaned_prod_dump_filtered_word_count_yake.parquet")

In [18]:
# dropping duplicates on both side

# previous shape of dfs
print(f"Filtered SDE shape before dropping duplicates: {filtered_sde.shape}")
print(f"Original SDE shape before dropping duplicates: {original_sde.shape}")

filtered_sde = filtered_sde.drop_duplicates(subset=["id"])
original_sde = original_sde.drop_duplicates(subset=["id"])

# after dropping duplicates
print(f"Filtered SDE shape after dropping duplicates: {filtered_sde.shape}")
print(f"Original SDE shape after dropping duplicates: {original_sde.shape}")

Filtered SDE shape before dropping duplicates: (331083, 8)
Original SDE shape before dropping duplicates: (545717, 10)
Filtered SDE shape after dropping duplicates: (331010, 8)
Original SDE shape after dropping duplicates: (545644, 10)

In [20]:
# printing the columns of both dataframes
print(f"Filtered SDE columns: {filtered_sde.columns.tolist()}")
print(f"Original SDE columns: {original_sde.columns.tolist()}")

Filtered SDE columns: ['id', 'url1', 'title', 'text', 'n_words', 'url2', 'predicted', 'prob_included']
Original SDE columns: ['id', 'url1', 'title', 'collection', 'treepath', 'sourcestr56', 'old_text', 'sourcebool3', 'text', 'yake']

In [21]:
# left do left join (filtered_sde, original_sde) based on id, so that i have all the columns
# i want columsn not in filtered_sde but in original_sde to be in the merged table: and dont want any suffixes
# so that i can use the original columns in the filtered_sde

merged_sde = pd.merge(filtered_sde, original_sde, on="id", how="left", suffixes=("", "_original"))
merged_sde.head()

,id,url1,title,text,n_words,url2,predicted,prob_included,url1_original,title_original,collection,treepath,sourcestr56,old_text,sourcebool3,text_original,yake
0,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/data/,ACTIVATE: Data – NASA Langley Research Center...,ACTIVATE: Data - NASA Langley Research Center ...,3975,b'/ACTIVATE/data/',1,0.989475,https://science.larc.nasa.gov/ACTIVATE/data/,ACTIVATE: Data – NASA Langley Research Center...,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Data,ACTIVATE: Data - NASA Langley Research Center ...,False,ACTIVATE: Data - NASA Langley Research Center ...,"[[""FLIGHTS"", 0.0025156622989489638], [""ACTIVAT..."
1,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/,ACTIVATE: Home – NASA Langley Research Center ...,ACTIVATE: Home - NASA Langley Research Center ...,4659,b'/ACTIVATE/',1,0.990293,https://science.larc.nasa.gov/ACTIVATE/,ACTIVATE: Home – NASA Langley Research Center ...,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Documentation,ACTIVATE: Home - NASA Langley Research Center ...,False,ACTIVATE: Home - NASA Langley Research Center ...,"[[""FLIGHTS"", 0.0024120919674993795], [""ACTIVAT..."
2,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/media/,ACTIVATE: Media – NASA Langley Research Cente...,ACTIVATE: Media - NASA Langley Research Center...,4458,b'/ACTIVATE/media/',1,0.985873,https://science.larc.nasa.gov/ACTIVATE/media/,ACTIVATE: Media – NASA Langley Research Cente...,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Documentation,ACTIVATE: Media - NASA Langley Research Center...,False,ACTIVATE: Media - NASA Langley Research Center...,"[[""FLIGHTS"", 0.002483062973658925], [""ACTIVATE..."
3,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/instrum...,ACTIVATE: Instruments – NASA Langley Research ...,ACTIVATE: Instruments - NASA Langley Research ...,4126,b'/ACTIVATE/instruments/',1,0.991540,https://science.larc.nasa.gov/ACTIVATE/instrum...,ACTIVATE: Instruments – NASA Langley Research ...,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Missions and Instruments,ACTIVATE: Instruments - NASA Langley Research ...,False,ACTIVATE: Instruments - NASA Langley Research ...,"[[""FLIGHTS"", 0.002533450856132368], [""ACTIVATE..."
4,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/education/,ACTIVATE: Education – NASA Langley Research C...,ACTIVATE: Education - NASA Langley Research Ce...,4192,b'/ACTIVATE/education/',1,0.992481,https://science.larc.nasa.gov/ACTIVATE/education/,ACTIVATE: Education – NASA Langley Research C...,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Documentation,ACTIVATE: Education - NASA Langley Research Ce...,False,ACTIVATE: Education - NASA Langley Research Ce...,"[[""FLIGHTS"", 0.002482532509504613], [""CLOUD"", ..."

In [22]:
# checking the shape of merged_df and of filtered_sde and original_sde
print(f"Merged SDE shape: {merged_sde.shape}")
print(f"Filtered SDE shape: {filtered_sde.shape}")
print(f"Original SDE shape: {original_sde.shape}")

Merged SDE shape: (331010, 17)
Filtered SDE shape: (331010, 8)
Original SDE shape: (545644, 10)

In [23]:
# now let's remove all columns of merged_df that has "_original" suffix
merged_sde = merged_sde.loc[:, ~merged_sde.columns.str.endswith("_original")]

merged_sde.head()

,id,url1,title,text,n_words,url2,predicted,prob_included,collection,treepath,sourcestr56,old_text,sourcebool3,yake
0,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/data/,ACTIVATE: Data – NASA Langley Research Center...,ACTIVATE: Data - NASA Langley Research Center ...,3975,b'/ACTIVATE/data/',1,0.989475,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Data,ACTIVATE: Data - NASA Langley Research Center ...,False,"[[""FLIGHTS"", 0.0025156622989489638], [""ACTIVAT..."
1,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/,ACTIVATE: Home – NASA Langley Research Center ...,ACTIVATE: Home - NASA Langley Research Center ...,4659,b'/ACTIVATE/',1,0.990293,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Documentation,ACTIVATE: Home - NASA Langley Research Center ...,False,"[[""FLIGHTS"", 0.0024120919674993795], [""ACTIVAT..."
2,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/media/,ACTIVATE: Media – NASA Langley Research Cente...,ACTIVATE: Media - NASA Langley Research Center...,4458,b'/ACTIVATE/media/',1,0.985873,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Documentation,ACTIVATE: Media - NASA Langley Research Center...,False,"[[""FLIGHTS"", 0.002483062973658925], [""ACTIVATE..."
3,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/instrum...,ACTIVATE: Instruments – NASA Langley Research ...,ACTIVATE: Instruments - NASA Langley Research ...,4126,b'/ACTIVATE/instruments/',1,0.991540,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Missions and Instruments,ACTIVATE: Instruments - NASA Langley Research ...,False,"[[""FLIGHTS"", 0.002533450856132368], [""ACTIVATE..."
4,/SDE/activate_aerosol_cloud_meteorology_intera...,https://science.larc.nasa.gov/ACTIVATE/education/,ACTIVATE: Education – NASA Langley Research C...,ACTIVATE: Education - NASA Langley Research Ce...,4192,b'/ACTIVATE/education/',1,0.992481,/SDE/activate_aerosol_cloud_meteorology_intera...,/Earth Science/ACTIVATE: Aerosol Cloud Meteoro...,Documentation,ACTIVATE: Education - NASA Langley Research Ce...,False,"[[""FLIGHTS"", 0.002482532509504613], [""CLOUD"", ..."

In [28]:
# lets remove any cmr data points
# shape of df before removing cmr data points
print(f"Merged SDE shape before removing CMR data points: {merged_sde.shape}")
merged_sde = merged_sde[~merged_sde["id"].str.startswith("/SDE/CMR_API/")]
# after removing cmr data points
print(f"Merged SDE shape after removing CMR data points: {merged_sde.shape}")

Merged SDE shape before removing CMR data points: (331010, 14)
Merged SDE shape after removing CMR data points: (292065, 14)

In [55]:
# let remove pds data points
# Shape of df before removing PDS data points
print(f"Merged SDE shape before removing PDS data points: {merged_sde.shape}")

merged_sde = merged_sde[merged_sde["treepath"] != "/Planetary Science/Planetary Data System (PDS)/"]

# after removing PDS data points
print(f"Merged SDE shape after removing PDS data points: {merged_sde.shape}")

Merged SDE shape before removing PDS data points: (292065, 14)
Merged SDE shape after removing PDS data points: (291926, 14)

In [57]:
# get the df that has qa generated
qa_generated_df = pd.read_parquet("/rhome/sawale/indus_traning/sentense_transformers/gen_data_stage3/instructor/data_v2/gpt-4o-mini/")

qa_generated_df.head()

,id,url1,title,text,prob_included,questions,context,search_terms,request_tokens,response_tokens,total_tokens,time_taken
2846,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210418.html,APOD: 2021 April 18 - Rainbow Airglow over the...,APOD: 2021 April 18 - Rainbow Airglow over the...,0.999830,[What causes the sky to glow in the phenomenon...,"[Airglow. Now air glows all of the time, but i...","[airglow phenomenon, gravity waves in atmosphe...",1050.0,615.0,1665.0,10.073934
3347,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap221011.html,"APOD: 2022 October 11 - Stars, Dust, Pillars, ...","APOD: 2022 October 11 - Stars, Dust, Pillars, ...",0.999830,[What structures are found within the Pelican ...,"[On the whole, the nebula appears like a bird ...","[Pelican Nebula structure, Herbig-Haro jets ef...",1055.0,625.0,1680.0,10.069554
1288,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap160322.html,APOD: 2016 March 22 - Rainbow Airglow over the...,APOD: 2016 March 22 - Rainbow Airglow over the...,0.999829,[What causes airglow in the Earth's atmosphere...,"[Airglow . Now air glows all of the time, but ...","[airglow phenomena, colors of airglow, gravity...",1049.0,580.0,1629.0,9.792861
976,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap150422.html,APOD: 2015 April 22 - Colorful Star Clouds in ...,APOD: 2015 April 22 - Colorful Star Clouds in ...,0.999828,"[What is the primary subject of the April 22, ...",[Discover the cosmos! Each day a different ima...,"[star forming region Cygnus, Gamma Cygni nebul...",1012.0,417.0,1429.0,6.736070
2767,/SDE/astronomy_picture_of_the_day/|https://apo...,https://apod.nasa.gov/apod/ap210125.html,APOD: 2021 January 25 - Southern Cross over Ch...,APOD: 2021 January 25 - Southern Cross over Ch...,0.999828,[What astronomical feature is depicted in the ...,[The featured image was taken last month in Ch...,"[Southern Cross visibility, Villarrica volcano...",1058.0,558.0,1616.0,8.383144

In [59]:
qa_generated_df["id"].nunique(), qa_generated_df.shape

(10000, (10000, 12))

In [60]:
# now lets remove data points from merged_df that is already in qa_generated_df
print(f"Merged SDE shape before removing QA generated data points: {merged_sde.shape}")
merged_sde = merged_sde[~merged_sde["id"].isin(qa_generated_df["id"].tolist())]
# after removing qa generated data points
print(f"Merged SDE shape after removing QA generated data points: {merged_sde.shape}")

Merged SDE shape before removing QA generated data points: (291926, 14)
Merged SDE shape after removing QA generated data points: (281926, 14)

In [63]:
# Checing for divisions in collection column

merged_sde["treepath"].str.split("/").str[:2].value_counts()

treepath
[, Planetary Science]                   93483
[, Earth Science]                       91959
[, Astrophysics]                        68047
[, Heliophysics]                        27780
[, Biological and Physical Sciences]      641
[, SDE]                                    16
Name: count, dtype: int64

In [71]:
# looks like for BPS, data is very low, we want to get BPS from unfiltered sde data

bps_df = original_sde[original_sde["treepath"].str.startswith("/Biological and Physical Sciences/")]
columns_not_in_bps = set(merged_sde.columns) - set(bps_df.columns)

# adding the columns that are not in bps_df to bps_df.setting value to None
for col in columns_not_in_bps:
    bps_df[col] = None

# before merging order columns in bps_df 
bps_df = bps_df[merged_sde.columns.tolist()]

# also need to remove all bps data points from merged_sde
print(f"Merged SDE shape before removing BPS data points: {merged_sde.shape}")
merged_sde = merged_sde[~merged_sde["treepath"].str.startswith("/Biological and Physical Sciences/")]
# after removing BPS data points
print(f"Merged SDE shape after removing BPS data points: {merged_sde.shape}")

# finally merge the bps_df with merged_sde
merged_sde = pd.concat([merged_sde, bps_df], ignore_index=True)

# checking the shape of merged_sde after merging bps_df
print(f"Merged SDE shape after merging BPS data points: {merged_sde.shape}")

/tmp/ipykernel_2200910/4206460495.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bps_df[col] = None
/tmp/ipykernel_2200910/4206460495.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bps_df[col] = None
/tmp/ipykernel_2200910/4206460495.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bps_df[col] = None
/tmp/ipykernel_2200910/4206460495.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bps_df[col] = None

Merged SDE shape before removing BPS data points: (281926, 14)
Merged SDE shape after removing BPS data points: (281285, 14)
Merged SDE shape after merging BPS data points: (282468, 14)

/tmp/ipykernel_2200910/4206460495.py:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  merged_sde = pd.concat([merged_sde, bps_df], ignore_index=True)

In [72]:
merged_sde["treepath"].str.split("/").str[:2].value_counts()

treepath
[, Planetary Science]                   93483
[, Earth Science]                       91959
[, Astrophysics]                        68047
[, Heliophysics]                        27780
[, Biological and Physical Sciences]     1183
[, SDE]                                    16
Name: count, dtype: int64

In [73]:
# creating new column called division from treepath
merged_sde["division"] = merged_sde["treepath"].str.split("/").str[1:2].str.join("/")

merged_sde["division"].value_counts()

division
Planetary Science                   93483
Earth Science                       91959
Astrophysics                        68047
Heliophysics                        27780
Biological and Physical Sciences     1183
SDE                                    16
Name: count, dtype: int64

In [78]:
# now sampling 2k datapoint from each division: exclude SDE division
# inclause where the sample count is larger than the availabel datapoints, just take all the datapointa
n_sample = 2205
sampled_sde = merged_sde[merged_sde["division"] != "SDE"].groupby("division").apply(lambda x: x.sample(n=min(n_sample, len(x)), random_state=42) if len(x) > n_sample else x).reset_index(drop=True)

sampled_sde["division"].value_counts()

/tmp/ipykernel_2200910/3207102957.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_sde = merged_sde[merged_sde["division"] != "SDE"].groupby("division").apply(lambda x: x.sample(n=min(n_sample, len(x)), random_state=42) if len(x) > n_sample else x).reset_index(drop=True)

division
Astrophysics                        2205
Earth Science                       2205
Heliophysics                        2205
Planetary Science                   2205
Biological and Physical Sciences    1183
Name: count, dtype: int64

In [ ]:
sampled_sde.shape

(10003, 15)

In [80]:
sampled_sde.head()

,id,url1,title,text,n_words,url2,predicted,prob_included,collection,treepath,sourcestr56,old_text,sourcebool3,yake,division
0,/SDE/cosmic_origins/|https://cor.gsfc.nasa.gov...,https://cor.gsfc.nasa.gov/news/2024/45_Roman_G...,News and Announcements - Roman Galactic Plane ...,Cosmic Origins (COR)\nSkip navigation and go s...,416,b'/news/2024/45_Roman_Galactic_Plane_Survey.php',1,0.990796,/SDE/cosmic_origins/,/Astrophysics/Cosmic Origins/,Documentation,Cosmic Origins (COR)\n\nSkip navigation and go...,True,"[[""MISSION"", 0.01058075672469502], [""SURVEY"", ...",Astrophysics
1,/SDE/hubble_space_telescope/|https://hubblesit...,https://hubblesite.org/contents/media/images/2...,Elliptical Galaxy NGC 4589 | HubbleSite,Elliptical Galaxy NGC 4589 | HubbleSite\nSkip ...,534,b'/contents/media/images/2015/28/3617-Image',1,0.998942,/SDE/hubble_space_telescope/,/Astrophysics/Hubble Space Telescope/,Images,Elliptical Galaxy NGC 4589 | HubbleSite\n\nSki...,False,"[[""IMAGE"", 0.02296526505263978], [""OBJECT"", 0....",Astrophysics
2,/SDE/stsci_space_telescope_science_institute/|...,https://www.stsci.edu/jwst/phase2-public/2511.pdf,"JWST Proposal 2511 (Created: Wednesday, April ...","JWST Proposal 2511 (Created: Wednesday, April ...",975,b'/jwst/phase2-public/2511.pdf',1,0.997065,/SDE/stsci_space_telescope_science_institute/,/Astrophysics/STScI: Space Telescope Science I...,Missions and Instruments,"\n\nJWST Proposal 2511 (Created: Wednesday, Ap...",False,"[[""COPI"", 0.0024100780900563733], [""COI"", 0.00...",Astrophysics
3,/SDE/ned_nasa_ipac_extragalactic_database/|htt...,https://ned.ipac.caltech.edu/level5/March20/Ma...,Multi-scale simulations of particle accelerati...,Multi-scale simulations of particle accelerati...,431,b'/level5/March20/Marcowith/Marcowith_contents...,1,0.995479,/SDE/ned_nasa_ipac_extragalactic_database/,/Astrophysics/NED: NASA IPAC Extragalactic Dat...,Documentation,Multi-scale simulations of particle accelerati...,False,"[[""ACCELERATION"", 0.030609566747167586], [""PAR...",Astrophysics
4,/SDE/cool_cosmos/|https://coolcosmos.ipac.calt...,https://coolcosmos.ipac.caltech.edu/ask/90-How...,How long does it take Jupiter to go around the...,How long does it take Jupiter to go around the...,216,b'/ask/90-How-long-does-it-take-Jupiter-to-go-...,1,0.999440,/SDE/cool_cosmos/,/Astrophysics/Cool Cosmos/,Documentation,How long does it take Jupiter to go around the...,False,"[[""JUPITER"", 0.00986148981876557], [""SUN"", 0.0...",Astrophysics

In [82]:
sampled_sde.to_parquet("/rhome/sawale/indus_traning/sentense_transformers/gen_data_stage3/samplw_2k_per_division.parquet", index=False)